// The typed message catalog — EVERY UI-chrome string. Key-first: each string carries BOTH locales
// adjacent ({ pt, en }), so there is no parallel per-locale block (which duplication detectors read as
// duplicated code) and adding a key can't miss a locale (the `satisfies` below makes it a compile error).
// The CV *content* is NOT here — it lives in src/data/profile.ts, authored bilingually in the same
// key-first shape and flattened by `resolveProfile`. Two catalogs, one convention: this one for chrome,
// that one for the CV, so chrome and content are in the visitor's language together.
import type { Locale } from './config';

/** One UI-chrome string in both locales. */
export interface Entry {
  pt: string;
  en: string;
}

// DOCUMENT TITLES (ADR-0045). A section group's `title` leaf is its document title, and it must LEAD with
// that section's `nav.*` label — the exact word the reader clicked. Anything after the label is optional
// and secondary. `nav` below is therefore the source of truth for the first words of five tabs, not just
// for the header bar; `messages.test.ts` asserts the relationship for every group that has a `title`, in
// both locales, so adding a section with a divergent title is a failing test rather than a review catch.
// The visible H1 (`heading`) is a DIFFERENT object and is deliberately editorial — never collapse them.
const strings = {
  nav: {
    // The skip link (#250). It lives here, not in an a11y group, because this catalog groups by WHERE a
    // string appears rather than why it exists — `nav.openMenu`, `locale.switch`, `share.linksLabel` and
    // `consent.notice` are all accessibility-only strings sitting in their surface group. A second axis
    // would give the next aria-label two plausible homes and make neither reliable to search.
    //
    // BOTH editions name the destination without ranking it — "content", not "main content". That is a
    // catalog-wide choice, not a translation note: en dropped "main" too.
    skipToContent: { pt: 'Pular para o conteúdo', en: 'Skip to content' },
    articles: { pt: 'Artigos', en: 'Articles' },
    portfolio: { pt: 'Portfólio', en: 'Portfolio' },
    contact: { pt: 'Contato', en: 'Contact' },
    profile: { pt: 'Perfil', en: 'Profile' },
    rampup: { pt: 'Ramp-up', en: 'Ramp-up' },
    architecture: { pt: 'Arquitetura', en: 'Architecture' },
    // The nav entry arrives with the first books, not with the route (#166). Slice 1 shipped `/library`
    // reachable by direct URL and the sitemap only, because pointing a reader at an empty shelf is worse
    // than not pointing — the label is what turns the surface from addressable into advertised.
    // The LABEL is bilingual; the SLUG is not (`/pt/library` · `/en/library`, ADR-0036's 2026-08-05
    // amendment), so "Biblioteca" is the one place a Portuguese reader meets the surface's own name.
    library: { pt: 'Biblioteca', en: 'Library' },
    openMenu: { pt: 'Abrir menu', en: 'Open menu' },
    closeMenu: { pt: 'Fechar menu', en: 'Close menu' },
  },
  locale: {
    // aria-label for the PT/EN toggle group.
    switch: { pt: 'Idioma', en: 'Language' },
  },
  footer: {
    // Accessible name for the version link. The visible text is a bare `v0.1.144` — conventional and
    // locale-neutral for a sighted reader, who gets the affordance from position and register. A screen
    // reader gets neither: it announces a link called "v0.1.144" with no context and no external-link
    // cue. So the number stays unlabelled on screen and the meaning lives here, which costs two catalog
    // entries and is the right trade in a file that is otherwise scrupulous about exactly this class of
    // thing (the skip link, the notice ordering, `tabIndex={-1}`).
    version: { pt: 'Notas da versão que está no ar (GitHub)', en: 'Release notes for the running build (GitHub)' },
  },
  adrTable: {
    // The generated decision index on /architecture (#318). Column headers and status labels live here
    // rather than in the markdown, because the TABLE is compiled from `docs/adr/` and only its chrome is
    // authored — putting the headers in each locale's markdown would mean the two editions could
    // disagree about what a column means while showing identical rows.
    // The PT caption says the records are in English, and the EN one does not — the asymmetry is the
    // point rather than a missing translation. Titles are canonical document names and stay in English
    // in both editions (a translated name would not exist at the other end of the click), so the PT
    // reader is the only one who meets 41 rows in a language the surrounding page is not. Signalling it
    // once in the caption costs a clause; leaving it unsaid makes the table look untranslated.
    // "generated … verified in CI", never "compiled at build". `npm run build` does NOT run `gen-adrs`
    // — the artifact is generated by its own command, committed, and checked by `adr-source.test.mjs`.
    // The paragraph above the table was corrected for exactly this and the caption was left carrying the
    // old claim, on the table itself, in both locales. Fixing one of two places is this slice's recurring
    // failure, and a caption is the copy a reader is most likely to take as the summary.
    caption: {
      pt: 'Índice de decisões, gerado a partir de docs/adr/ e conferido no CI — os registros são em inglês',
      en: 'Decision index, generated from docs/adr/ and verified in CI',
    },
    colId: { pt: 'ADR', en: 'ADR' },
    colTitle: { pt: 'Decisão', en: 'Decision' },
    colStatus: { pt: 'Situação', en: 'Status' },
    accepted: { pt: 'aceita', en: 'accepted' },
    superseded: { pt: 'substituída', en: 'superseded' },
    proposed: { pt: 'proposta', en: 'proposed' },
    rejected: { pt: 'rejeitada', en: 'rejected' },
    // Appended to a status, not replacing it: a decision that stands but has been revised is neither
    // plainly "accepted" nor superseded, and collapsing it to either loses the bit a reader needs.
    amended: { pt: 'emendada', en: 'amended' },
  },
  diagram: {
    // The expand affordance on every figure of /architecture (#473). Two strings, and both are
    // deliberately ONE WORD: the control sits in a `text-xs uppercase` row above a drawing, and the
    // accessible name is built as `"<this>: <the figure's caption>"` — the captions on this page run to
    // eighty characters, so anything longer here is read before the thing it is about.
    //
    // WHY AN ACCESSIBLE NAME AT ALL, when the visible label already says it: the page carries FOUR of
    // these controls, and four buttons called "Ampliar" are indistinguishable to a screen-reader user
    // moving by control. The caption is what tells them apart, and it is the same word a sighted reader
    // has under the drawing. WCAG 2.5.3 holds because the long form starts with the short one — and the
    // VERB LEADS deliberately: a voice-input user says the word they can SEE, so "Ampliar: <caption>"
    // is reachable by voice and "<caption>: Ampliar" is not. Do not reorder it.
    //
    // BOTH EDITIONS PROMISE MAGNIFICATION, and getting there took a correction worth recording, because
    // the first version gave the two editions different promises. "Ampliar" was chosen for pt on the
    // argument that "expandir" is the ACCORDION word in BR interface Portuguese — an unfold, not a zoom
    // — and this control opens the figure at its natural size rather than revealing hidden content. en
    // was then left as "Expand", with the claim that the same ambiguity did not bite there.
    //
    // IT BITES HARDER IN ENGLISH. "Expand"/"Collapse" is the canonical disclosure pair, and it is the
    // word the aria-expanded attribute is named after — an attribute DiagramFigure sets on this very
    // button. So the vaguer promise was going to the edition every launch surface links to, while the
    // Portuguese reader got the clearer one. "Enlarge" is the exact English of "Ampliar" and carries no
    // disclosure history, so the pair now says one thing in two languages.
    //
    // aria-expanded STAYS regardless: it is the correct attribute for a control that opens a dialog,
    // whatever verb the visible label uses. The ARIA name is not the copy.
    expand: { pt: 'Ampliar', en: 'Enlarge' },
    collapse: { pt: 'Fechar', en: 'Close' },
  },
  marquee: {
    // The key stays `subjects` — renaming it would touch every call site for no reader benefit —
    // but the LABEL is now "Stack", because that is what the strip lists. See Marquee.tsx.
    subjects: { pt: 'Stack', en: 'Stack' },
  },
  hero: {
    badge: { pt: 'Conteúdo técnico aberto', en: 'Open technical content' },
    badgeAccent: { pt: '▶ Da vida pessoal à produção', en: '▶ From personal life to production' },
    taglineLead: { pt: 'Aprenda a construir com IA —', en: 'Learn to build with AI —' },
    taglineAccent: { pt: 'do dia a dia à produção', en: 'from everyday life to production' },
    bodyLead: {
      pt: 'Compartilho o que aprendo construindo com IA — de experimentos que automatizam a',
      en: 'I share what I learn building with AI — from experiments that automate',
    },
    bodyStrong1: { pt: 'vida pessoal com Claude Cowork', en: 'personal life with Claude Cowork' },
    bodyConnector: { pt: 'a', en: 'to' },
    bodyStrong2: { pt: 'agentic development', en: 'agentic development' },
    bodyTail: {
      pt: '. Trade-offs reais e código aberto pra você aplicar, seja na sua rotina ou na sua empresa. O objetivo é te fazer construir melhor — quem escreve isso é consequência, não o ponto.',
      en: '. Real trade-offs and open source for you to apply, whether in your routine or at your company. The goal is to help you build better — who writes it is a by-product, not the point.',
    },
  },
  tracks: {
    pessoal: { pt: 'Vida pessoal', en: 'Personal life' },
    engenharia: { pt: 'Engenharia', en: 'Engineering' },
  },
  articles: {
    headingBold: { pt: 'Artigos', en: 'Articles' },
    headingRest: { pt: 'pra você aplicar', en: 'to put to use' },
    // The `· videos embedded in the text` half was dropped (owner, 2026-07-31). Both editions, because
    // this is one string with two renderings, not two decisions.
    //
    // The reason is stronger than "it promised a format rather than a payoff", which is what this
    // comment said first: NO ARTICLE DELIVERED IT. The capability exists (`hasVideo` in the
    // frontmatter, and the badge below fires per item) but not one published article sets it — the
    // embeds are on /ramp-up, a different route. So the storefront's highest-traffic section
    // advertised a property that zero of its rows carried. That is a capability stated as track
    // record, which the positioning rules out.
    //
    // The per-item `hasVideo` badge is the right home for the claim, and stays: it can only ever be
    // true, because it is rendered from the article that has one.
    subtitle: {
      pt: 'Escrita técnica com trade-offs explícitos',
      en: 'Technical writing with explicit trade-offs',
    },
    filtersLabel: { pt: 'Filtrar por trilha', en: 'Filter by track' },
    filterAll: { pt: 'Tudo', en: 'All' },
    takeaway: { pt: 'Você sai sabendo', en: "What you'll walk away with" },
    hasVideo: { pt: '▶ vídeo no artigo', en: '▶ video in the article' },
    read: { pt: 'Ler artigo', en: 'Read article' },
    viewOnLinkedin: { pt: 'Ver no LinkedIn', en: 'View on LinkedIn' },
    empty: { pt: 'Ainda não há artigos nesta trilha.', en: 'No articles in this track yet.' },
  },
  // The ramp-up page's chrome. Its BODY is markdown-in-repo, authored in both locales
  // (content/rampup.pt.md · content/rampup.en.md), so chrome and content are always in the same
  // language — the parity rule, not an interim.
  rampup: {
    heading: { pt: 'Ramp-Up — Virando AI Engineer', en: 'Ramp-Up — Becoming an AI Engineer' },
    // Document title (ADR-0045; the site name is appended by useDocumentHead). Already compliant before
    // the convention existed — it leads with `nav.rampup` ("Ramp-up") and qualifies after — so it is left
    // alone deliberately. Rewriting a conforming title would have regenerated an OG card scrapers have
    // already pinned (ADR-0041), for no reader gain.
    title: { pt: 'Ramp-up para AI Engineer', en: 'Ramp-up to AI Engineer' },
    kicker: { pt: 'Plano aberto · em andamento', en: 'Open plan · in progress' },
    metaDescription: {
      pt: 'O plano que montei para migrar de arquiteto de aplicações cloud para AI Engineer: o raciocínio, os cinco pilares, o roadmap de 6–12 meses e as fontes que estou realmente usando.',
      en: 'The plan I built to move from cloud application architect to AI Engineer: the reasoning, the five pillars, the 6–12 month roadmap, and the sources I am actually using.',
    },
  },
  // The architecture page's chrome. Its BODY is markdown-in-repo, authored in both locales
  // (content/architecture.pt.md · content/architecture.en.md), so chrome and content are always in the
  // same language — the parity rule. The page is an orientation layer that LINKS canonical detail
  // (the ADRs, the two public repos, catalog-ready) rather than restating it.
  architecture: {
    heading: { pt: 'Arquitetura — a planta, em aberto', en: 'Architecture — the blueprint, in the open' },
    // Document title (ADR-0045; the site name is appended by useDocumentHead). This is the defect the
    // convention was written for: the tab said "Como este site é construído" and the word the reader
    // clicked — Arquitetura — appeared nowhere in it, so with several tabs open the page could not be
    // found by the name it was opened under. The tail is the OLD title, kept rather than dropped: this
    // string is also the og:title, the ShareButton title and the JSON-LD headline (MarkdownPage), and a
    // bare "Arquitetura" would have made an unfurled card thinner than the one it replaces.
    // The HEADING is untouched and stays editorial. Different objects, different jobs — see ADR-0045.
    title: { pt: 'Arquitetura — como este site é construído', en: 'Architecture — how this site is built' },
    kicker: { pt: 'A planta · aberta', en: 'The blueprint · open' },
    metaDescription: {
      // `agent-led verification` stays English in both locales, like `agentic` and `AI-native` (#245).
      // This string translated it while `architecture.pt.md` keeps the term with a gloss — so the pt
      // reader met the canonical term in the body and NEVER in the OG card, which is the text a scraper
      // pins. One term, two treatments, and the split landed in the surface with the worst correction
      // cost. The gloss stays in the body, where there is room to teach it.
      // Term FIRST, stack after. It used to sit around character 120 — inside the window LinkedIn, X and
      // SERP previews cut — so the fix that put the canonical term in the pt card left it invisible in a
      // large share of the cards it was meant to fix. The en string reached it earlier and was safer,
      // which is why the defect was only in one edition.
      // "as decisões que sustentam peso" / "the load-bearing decisions", NOT "cada" / "every" — the page
      // this describes qualifies it twice in both editions, and repoCards.ts carries the same correction on
      // the card that links the same library. A meta line is the one place the qualifier is cheapest to
      // drop and the claim hardest for a reader to check against the page it summarises.
      // REWRITTEN WITH THE BODY, in the same diff, and that is the point rather than a nicety (#448).
      // Nothing couples this string to `architecture.{pt,en}.md`, so a restructure that changes what the
      // page is ABOUT leaves the OG card describing the page that used to be here — and the card is the
      // text a scraper pins on first fetch.
      // THE ~160-CHARACTER WINDOW IS THE RULER, NOT THE TOTAL LENGTH (#448). The first rewrite of this
      // string followed the body's spine literally — term, then the three pillars by name, then the two
      // checkable claims — and got LONGER (pt 239 → 258, en 224 → 247) on the slice whose subject is
      // compression. Worse, it broke inside the pillar list at the truncation LinkedIn, X and SERP
      // previews cut, so the monthly cost and the ADRs — the two claims this string exists to carry,
      // per the note above — fell outside the window in both editions. A reader arriving from a post
      // saw neither.
      // So: OPEN ON THE PROBLEM, matching the body's own first heading rather than the old completeness
      // framing ("Como este site é construído" / "How this site is built" survives as the document
      // TITLE, which is a different object — see the title note above). The pillar list is dropped, not
      // shortened: it is what pushed the checkable claim past the cut.
      //
      // THE FIRST ATTEMPT AT THAT OPENING BROKE THE TERM-FIRST RULE FOUR LINES ABOVE, and its own
      // comment then claimed the rule was satisfied. Measured on that string: `agent-led verification`
      // started at **pt 119 / en 101**, against **pt 43 / en 28** in the string it replaced — so the pt
      // edition landed on ~120, the exact position the rule names as the failure, in the exact edition
      // the rule says the failure was in. A record asserting a rule holds when it does not is worse
      // than the regression it describes, which is why this note carries the numbers rather than a
      // verdict.
      //
      // THE TWO PROPERTIES BOTH FIT, so no trade was needed and none is claimed. Term first, the
      // problem immediately after the colon (the hook survives, one clause later), pillar list still
      // dropped. Measured on the strings below:
      //
      //   pt — len 196 · `agent-led verification` at 15–37 · `R$ 34,31/mês de conta` complete at 155
      //   en — len 193 · `agent-led verification` at  3–25 · `a USD 6.57/month bill` complete at 143
      //
      // THOSE FIGURES MOVED ON THE SINGULAR CORRECTION, and they are re-measured rather than carried
      // over. The card said "ferramentas" / "tools", plural, after the owner had already corrected the
      // body to `a ferramenta` / `the tool`, singular — the card was quoting the page's strongest
      // sentence in the version he ruled wrong, on the surface a reader meets first. pt gained one
      // character (`ferramentas` → `a ferramenta`) and en lost one (`tools` → `tool`), so the claim now
      // completes at 155 (pt) and 143 (en) against the same 160 window, and the term still ends at 37
      // and 25 against the 120 bound. Both properties hold with room; neither was assumed.
      //
      // THE PT FIGURE IS BRL AND THE EN FIGURE IS USD, deliberately — the pt EDITION of the page
      // regionalises its cost section (owner's request) and this card is the same claim's OG surface, so
      // a USD card over a BRL page would contradict the page a reader lands on. Both numbers are the
      // same bill at R$ 5,222/USD, the 2026-08-14 close, stated in the page body where the reader can
      // reverse any line back to the invoice.
      // The pt figures above did NOT move on that change: `USD 6,57` and `R$ 34,31` are both 8
      // characters, so length and every position held exactly. Measured, not assumed — the term ends at
      // 37 against the 120 bound and the claim completes at 154 against the 160 window.
      //
      // Both editions therefore carry the canonical term far inside every preview cut AND one checkable
      // claim — the monthly bill — inside the first 160 characters. The ADR clause still sits after the
      // cut deliberately: fitting it too costs the opening, and the opening is the hook.
      // `agent-led verification` still leads the stack and still stays English in pt, per the two rules
      // above.
      //
      // The term's POSITION is now gated, not only its presence: `e2e/per-locale.spec.ts` asserts it
      // ends before character 120 in the served `og:description` of both editions. Containment alone is
      // what let the regression above ship green.
      pt: 'Um dev-loop de agent-led verification: a ferramenta de desenvolvimento agêntico na mão e mesmo assim de fora do hype. O que saiu daí: R$ 34,31/mês de conta e as decisões que sustentam peso em ADR.',
      en: 'An agent-led verification dev-loop: the agentic development tool in hand and still outside the hype. What came out of it: a USD 6.57/month bill and the load-bearing decisions on record as ADRs.',
    },
    //
    // THE TEASER CARD (#450, slice 2) — what replaces the landing band shipped in #461, after the owner's
    // verdict on it: "você descaracterizou a home". The band was a <section> between the Hero and the grid,
    // and the objection was to the OBJECT, not to its words: a band changes the landing's shape, and the
    // landing's shape is the articles. What he asked for instead is a card that looks exactly like an
    // article card, is pinned at the top of that list, is outside the track filter, and goes straight to
    // /architecture — "deveria ser como artigo, mas não é um artigo pois quero direcionar direto pra
    // seção arquitetura".
    //
    // THE SAME TWO CONSTRAINTS THE BAND COPY WAS WRITTEN UNDER STILL HOLD, and they are restated here
    // rather than inherited by proximity, because the band leaves they were written on (`bandKicker`,
    // `bandHeading`) are deleted in this same slice and take their notes with them:
    //   1. NO WORD MAY DEPEND ON THE DATE — no "novo", no "lançamento", no "just shipped". The card is
    //      permanent furniture on the front door, not a launch announcement; it must read correctly in
    //      three months, and nothing in this repo would ever raise a stale one.
    //   2. THE READER IS THE SUBJECT, NEVER THE OWNER. Higher on the same page the Hero's body ends —
    //      published, in both editions — with "quem escreve isso é consequência, não o ponto." A card
    //      leading with the owner contradicts a sentence on the screen it sits on.
    //
    // These three leaves stay in the `architecture` group for the same reason the band's two did:
    // `messages.test.ts` derives ADR-0045 coverage from every TOP-LEVEL group carrying a `title` leaf and
    // pins the set to ['architecture','library','portfolio','rampup'], so a new `home`/`teaser` group
    // would either red that test or need a title it has no business having. And semantically, copy ABOUT
    // this destination belongs beside the destination's own `heading`/`kicker`, where a drift between
    // them is visible in one screen of this file.

    // THE TRACK-CHIP SLOT, and it is the single load-bearing string here: it is what stops the card being
    // a lie. The chip beside it on every other row is a TRACK — "Vida pessoal" / "Engenharia" — so a
    // reader scanning the column reads this slot as "what kind of writing is this". The answer has to be
    // "it isn't writing", said before the click, in chip-sized space.
    //
    // NOT the bare noun ("Seção" / "Section"), which in a column of track names reads as a THIRD track.
    // The possessive half is what disambiguates, and it is the half the retired band's kicker also carried
    // ("Seção deste site"). Shortened from that by one word: a chip renders mono-uppercase at text-xs
    // beside "VIDA PESSOAL" (12 chars) and "ENGENHARIA" (10), and "SEÇÃO DESTE SITE" (16) is wider than
    // anything the row has ever held. "SEÇÃO DO SITE" (13) / "SITE SECTION" (12) sit inside that
    // established width and lose nothing the sentence was doing.
    cardTrack: { pt: 'Seção do site', en: 'Site section' },
    // THE TITLE, carried over VERBATIM from the retired band's heading — deliberately, not by inertia. That
    // string's recorded job was "what this section is FOR to someone deciding to click", as opposed to
    // `heading`, which says what the page IS to someone already there. A card title in a list of article
    // titles is that first job exactly, so the string is being moved to the surface it was already
    // written for rather than rewritten for a surface it already fits.
    //
    // Its two sourcing notes travel with it and are not re-derived here: the reader must meet the
    // DESTINATION'S OWN NAME first (the word the click lands on is "Arquitetura" — the same rule ADR-0045
    // applies to document titles, and a card that renames the section is that defect one screen earlier),
    // and neither noun is invented — "a máquina" is the site's own word for this page
    // (architecture.pt.md:60 and :211 say it of itself — a third citation, to
    // content/blog/engineer-the-loop.pt.md:30, was dropped when that article was withdrawn on
    // 2026-08-21; the claim never rested on it alone), and
    // "replicar" is the page's own closing H2 ("Replique para o seu contexto" / "Replicate it for your
    // own context").
    cardTitle: {
      pt: 'Arquitetura — a máquina inteira, e como replicá-la',
      en: 'Architecture — the whole machine, and how to replicate it',
    },
    // THE EXCERPT — the hook, and the leaf the band never had. It sits where the article excerpts sit and
    // is written to their length and register: one inventory sentence, one sentence that lands the
    // posture (compare my-commitment's "O primeiro post. Por que este espaço existe…"; the second
    // comparand, engineer-the-loop's two-beat "não é uma ideia nova… é uma ideia antiga", was withdrawn
    // from the site on 2026-08-21 and is quoted here from the record rather than from a live file).
    //
    // EVERY CLAIM IS THE PAGE'S OWN, in both editions. "o que foi cortado e por quê" ← "não foi
    // construída enxuta. Foi construída inteira e depois cortada" plus the five superseded ADRs it links.
    // "as decisões que sustentam peso registradas em ADR" is `metaDescription`'s phrasing above, kept
    // WORD FOR WORD including the qualifier: the page qualifies this twice in both editions and the note
    // on that string already records why "cada" / "every" is the wrong word here. The closing sentence is
    // near-verbatim body text — pt "o que está aqui é o setup inteiro, não só a conclusão a que ele
    // chegou", en "what is here is the whole setup, not only the conclusion it reached".
    //
    // THE BILL IS NAMED WITHOUT ITS NUMBER, and that is the one deliberate softening. "quanto custa por
    // mês" / "what it costs a month" points at the strongest checkable claim on the destination; printing
    // "USD 6,57" here would put a figure that moves with an AWS invoice onto a card with no retirement
    // step, which is constraint 1 above arriving through the back door. The page prints the number, dated
    // and in context, which is where a number that moves belongs.
    //
    // "levar o que servir pro seu contexto" was NOT used, though it is the page's closing ask: the title
    // one line above already ends on "como replicá-la", and the same payoff twice in three lines reads as
    // a card unsure it landed. The excerpt takes the inventory; the title keeps the replication claim.
    cardExcerpt: {
      pt: 'O que foi construído, o que foi cortado e por quê, quanto custa por mês, e as decisões que sustentam peso registradas em ADR. O setup inteiro, não só a conclusão a que ele chegou.',
      en: 'What got built, what got cut and why, what it costs a month, and the load-bearing decisions on record as ADRs. The whole setup, not only the conclusion it reached.',
    },
    // THE CONTROL LABEL IS `nav.architecture`, AND THERE IS DELIBERATELY NO LEAF FOR IT HERE. Written as
    // a note rather than a string because the absence is the decision, and an absence with no record
    // reads as an oversight to whoever adds the missing key later.
    //
    // What it must not be: `articles.read` — "Ler artigo" / "Read article" — which is the objection that
    // killed the earlier proposal to reuse the article row unchanged. A control stating something the
    // click does not do is a published untruth, on the site's highest-traffic block.
    //
    // What a NEW leaf would buy, and why it is not worth it. Its only gain over `nav.architecture` is
    // grammatical parallelism with the "Ler artigo" controls beside it — and that parallelism is the one
    // property this card should not have. Every other signal on the row (the chip, the title, the
    // excerpt) works to say "this is not writing"; a control that reads as a NOUN where its neighbours
    // read as verbs is that same signal, for free, in the last place a reader looks before clicking.
    // Against that: #315 recorded the rule that the reader meets ONE word for one destination, and
    // `nav.architecture` is already what the nav entry and the Hero's leading control both render. A
    // fourth label for /architecture, duplicating a word the catalog already publishes, is a second
    // source of truth that can only ever drift.
    //
    // The word repeating inside the card ("Arquitetura —" in the title, "ARQUITETURA" on the control) is
    // accepted, not overlooked: the retired band carried exactly that repetition, shipped with it, and it
    // is what the one-word rule costs.
  },
  // The Biblioteca / Library surface (#166) — a curated reading shelf. Unlike /ramp-up and /architecture
  // there is no markdown body: the page is chrome around typed data (src/data/library.ts), so ALL of its
  // words live here, including the empty state.
  //
  // The LABEL is bilingual ("Biblioteca" / "Library"); the ROUTE it is reached at is decided in
  // ADR-0010, not here. Nothing in this group encodes a path, so the routing decision cannot reach it.
  library: {
    heading: { pt: 'Biblioteca — o que eu leio, e o que ficou', en: 'Library — what I read, and what stuck' },
    // Document title (ADR-0045; the site name is appended by useDocumentHead). The bare noun, not the
    // heading: a <title> is read in a tab and in a SERP, where the subtitle is what gets truncated away
    // anyway. This key is where the convention was already being followed by instinct — ADR-0045 only
    // wrote down what it was doing and made it checkable.
    title: { pt: 'Biblioteca', en: 'Library' },
    // `em montagem` / `being put together`, not `em curadoria` / `being curated`. Two reasons, and the
    // second is why it changed: *being curated* is everyday English while `em curadoria` in pt-BR is
    // editorial/museum register, so the pt side was a status label imported from the en — the one calque
    // in this group, running pt-ward. And it disagreed with the verb the empty state already uses.
    kicker: { pt: 'Estante · em montagem', en: 'Shelf · being put together' },
    // EVERY SENTENCE HERE STATES A RULE, NEVER THE CONTENTS. A contents sentence is false at zero entries
    // and true at twenty; a rule sentence is true at both. That is not only about being correct today —
    // a description that must be re-edited when the books land is a SECOND regeneration of an
    // already-pinned OG card, which is the cost this file keeps warning about. Written as a rule, it is
    // written once.
    //
    // "só entra o que eu terminei" / "only what I have finished gets in" is doing real work, not
    // decoration: the shelf carries a rating on every entry, and a rating on an unread book would be a
    // claim the reader cannot check. The data model has no `status` field precisely because only-read is
    // the model (owner, 2026-08-05), so the copy states the same rule the type enforces.
    //
    // It states that rule POSITIVELY rather than as "não é lista de leitura" / "not a reading list",
    // which the first draft used. That contrast defined this surface against `/ramp-up`, which publishes
    // books marked *(reading)* and *(on my list)* — a reading list, by the owner's own hand, one route
    // away. It lost nothing to drop: the rule was the payload, the contrast only its framing, and the
    // framing would have read worst exactly when the two surfaces get cross-linked.
    intro: {
      pt: 'Uma estante curta: os livros por trás de como eu trabalho. Cada um entra com nota de 1 a 5 e uma frase do que eu tirei dele — e só entra o que eu terminei.',
      en: 'A short shelf: the books behind how I work. Each one goes up with a 1–5 rating and a line on what I took from it — and only what I have finished gets in.',
    },
    // THIS ONE STRING IS THE SERP SNIPPET, and it is why the rule form above is not a style preference.
    // `useDocumentHead` puts it in three places at once — <meta name="description">, `og:description`
    // and `twitter:description`. `/library` is in STATIC_ROUTES, and `gen-sitemap.mjs` derives the
    // sitemap from that same enumeration, so both URLs are advertised to Google FROM MERGE with no
    // in-site link required. Having no nav entry removes the social pinning exposure; it does not touch
    // the search exposure. The realistic day-1 reader is not someone forwarding a card — it is someone
    // Google showed this line, landing on a shelf.
    //
    // The first draft said "cada livro com nota de 1 a 5 e o que eu tirei dele" — a populated shelf, in
    // the present tense, on a shelf with zero entries. Untrue at the moment of publication, which is a
    // different class from a true sentence that ages: the OG-pinning mechanism sets the COST of an
    // error, never its CLASS, and there is no moment at which that card was correct to pin.
    metaDescription: {
      pt: 'A estante por trás de como eu trabalho: IA, sistemas distribuídos, infraestrutura e engenharia de software. Cada livro entra com nota de 1 a 5 e o que eu tirei dele — e só entra o que eu li.',
      en: 'The shelf behind how I work: AI, distributed systems, infrastructure and software engineering. Every book goes up with a 1–5 rating and what I took from it — and only what I have actually read gets in.',
    },
    // The empty state, and it is DELIBERATE COPY rather than a fallback nobody expected to render. The
    // surface ships before the books (#166 slice 1), because the alternative — a placeholder book — is
    // reader-facing prose in the owner's voice that ships and is then removed, and it is exactly what an
    // OG scraper pins permanently (ADR-0005/0041). Chrome can say "not yet"; a fake book cannot.
    // `Esta estante` / `This shelf`, with the demonstrative, because `/ramp-up` already uses the bare
    // definite noun for a DIFFERENT set — "Metade dessa estante ainda está saindo capítulo por capítulo"
    // / "Half of this shelf is still shipping chapter by chapter", over six named titles. A reader who
    // saw that page first would meet a contradiction of the article: that shelf is not being put
    // together, it is listed. One word localises the noun and removes the collision.
    //
    // NO SCHEDULE. The first draft said "em breve" / "soon" — a date nobody committed to, on a page no
    // gate is watching, which goes quietly false the day slice 2 slips and nothing in CI can say which
    // day that is. The rule ("um a um, conforme eu termino") is true forever and is the better register
    // besides. It also does not apologise for shipping an empty surface, which was the risk here: the
    // owner's habit is to under-claim, and this copy declines to.
    empty: {
      pt: 'Esta estante ainda está sendo montada. Os livros entram um a um, conforme eu termino, cada um com nota e o que eu tirei dele.',
      en: 'This shelf is still being put together. Books go up one at a time, as I finish them, each with a rating and what I took from it.',
    },
    // The rating meter's accessible name. `{rating}` and `{max}` are substituted by RatingMeter, `{max}`
    // from the same constant that generates the squares — so the announced scale cannot disagree with the
    // drawn one. A screen reader is the only way this value reaches a reader who cannot see the fill,
    // which is why it is a catalog string and not the hardcoded English literal `LevelMeter` still uses.
    ratingLabel: { pt: 'Nota {rating} de {max}', en: 'Rated {rating} out of {max}' },
  },
  portfolio: {
    heading: { pt: 'Portfólio', en: 'Portfolio' },
    // Document title (ADR-0045). Identical to `heading` TODAY, and that coincidence is precisely why it
    // is now its own key: the page used to pass `portfolio.heading`, so the day the heading grows a
    // subtitle — every other section's already has one — the tab would silently stop being the word the
    // reader clicked. Same string, a source that cannot drift.
    title: { pt: 'Portfólio', en: 'Portfolio' },
    // `se formam`, not `graduam`: in BR Portuguese this sense of `graduar` is pronominal, so the bare
    // form is the English intransitive wearing a Portuguese ending — the same defect class as the
    // "clarear a barra" draft this section's bar line went through. Shipped copy, found only because
    // the line above it was under review.
    // Dropped the definite article in both editions too: "as automações" / "the automations"
    // presupposes a set the reader has not been shown.
    intro: {
      pt: 'Código aberto pra você estudar, clonar e usar. Cresce conforme automações se formam.',
      en: 'Open source for you to study, clone and use. It grows as automations graduate.',
    },
    // The BAR (#246). With one item in the catalog — and that item being this site — the page reads as a
    // catalog that has not started. Saying inclusion is earned turns "the only item" into "the first item
    // that cleared the bar", which is a different claim to someone deciding whether the list is thin or
    // selective. It costs nothing to keep true: `docs/catalog-ready.md` already exists and is public, so
    // the sentence points at something checkable rather than making a promise to maintain.
    // Three drafts, and each one failed differently — worth recording, because the failures are the
    // reasoning:
    //
    // 1. "clarear a barra" was not Portuguese. `clarear` means to lighten; it was a calque of "clear the
    //    bar" carrying nothing of crossing a threshold.
    // 2. "conquista seu lugar passando pela régua" fixed the language and matched `/architecture`'s NOUN
    //    (pt "A régua", en "The bar") but not its construction — there the verb takes the DOCUMENT
    //    ("passa por catalog-ready.md"). So the surfaces shared a word, not a shape. `passar pela régua`
    //    is also not the BR form (that is `passar na régua`), and `conquista seu lugar` sat a register
    //    above this section's voice, which is second-person and warm two lines up.
    // 3. Both of those asserted an AUDIT — "each project earned its place" quantifies over the catalog's
    //    contents, so a reader can falsify it by checking the one item against the linked checklist. They
    //    can, today: #252. A sentence whose job is to RAISE scrutiny has to survive being scrutinised.
    //
    // So this states the GOVERNANCE rather than the audit — the rule, not a verdict on each item.
    //
    // Be precise about what that buys, because an earlier version of this comment overclaimed it: it is
    // NOT logically weaker. "Nothing enters without passing X" is the contrapositive of "everything here
    // passed X" — same truth conditions, falsified by the same single counterexample. What it buys is
    // rhetorical: it foregrounds the standard instead of inviting an item-by-item audit, and it drops a
    // merit claim that read as self-congratulation with a one-item shelf. The claim still has to be TRUE
    // on the day it ships, which is why #252 comes first.
    //
    // en went through one more pass than pt. `clear` wants a threshold noun — you clear a bar, a hurdle —
    // and with the noun dropped it was left governing a bare filename, with a colon stranding a transitive
    // verb before the break. `/architecture` gets away with `clears docs/catalog-ready.md` only because an
    // appositive supplies the noun right after. So en uses a verb that natively takes a document as its
    // object, and `gets listed` for the flat, un-Latinate register `entrar` already has in pt.
    // FOURTH draft, and the third failure was the interesting one — it was not about language.
    //
    // "Nothing gets listed here without passing X" is a universal over the shelf's CONTENTS, and
    // /architecture publishes, in both editions, that "this site is the one entry that did not come
    // through it". With a one-item shelf, that item IS the exception — so a reader visiting both
    // surfaces meets a contradiction, and the link makes it worse rather than better, because clicking
    // it lands them on the section that spells the exception out.
    //
    // The scoping work in #255/#256/#258 did not rescue the universal; it made it harder to stand
    // behind, by putting the carve-out into published copy.
    //
    // AMENDED #407, and the amendment is why this comment is worth keeping rather than shortening.
    // The paragraph quoted two paragraphs up — "this site is the one entry that did not come through
    // it" — was CUT from both editions of /architecture in that PR, on the owner's paragraph-by-
    // paragraph review. So the sentence a reader could catch this copy on is no longer published.
    //
    // THAT CHANGES NOTHING HERE, and the reason is the distinction this comment already turns on:
    // the objection was never that the exception was *published*, it was that the exception is
    // *true*. It still is — `catalog.ts` lists `tadeumendonca-io`, and that entry's own comment
    // records that it is the shelf rather than an item on it. Deleting the disclosure removed the
    // reader's evidence, not the counterexample. A universal here would now be a claim that is false
    // and no longer conveniently falsifiable, which is worse than the state this draft was written
    // to escape.
    //
    // #407 also had to fix the SAME defect on /architecture, in the other direction: cutting that
    // paragraph left the feature bullet reading "a project enters by clearing the written bar" — an
    // unqualified universal, with the bar's own link stapled into it. It now names the bar and
    // quantifies nothing, matching this key. Both surfaces are back on one shape; the shape is the
    // one below, and it is the same shape for the same reason.
    //
    // So this names the STANDARD and quantifies nothing: there is a bar for getting listed, here it is,
    // go read it. It still does #246's job — it turns "the only item" into "a shelf with an entry
    // requirement" — and it is true whatever the shelf currently holds, including while the shelf holds
    // its own exception. It also matches /architecture's label exactly (pt "A régua", en "The bar"),
    // which is the cross-surface consistency the earlier drafts kept missing.
    bar: {
      pt: 'A régua pra entrar aqui:',
      en: 'The bar for getting listed here:',
    },
    // The link text is the filename, deliberately untranslated — it names the artifact rather than
    // describing it, so there is nothing to keep in sync between editions.
    // Path form, matching how `/architecture` names the same artifact. These are the two surfaces most
    // likely to be read together, and one document with two names across them is a small, avoidable drift.
    barLink: { pt: 'docs/catalog-ready.md', en: 'docs/catalog-ready.md' },
    payoff: { pt: 'O que você tira disso', en: 'What you take away' },
    statusLive: { pt: 'Live', en: 'Live' },
    statusWip: { pt: 'WIP', en: 'WIP' },
    viewGithub: { pt: 'Ver no GitHub', en: 'View on GitHub' },
    viewLive: { pt: 'Ver ao vivo', en: 'View live' },
    // Only for a card that shows NO tag (#329). Where a tag is shown it IS the label — a version string
    // is the same in every edition, so it is not localized, exactly like `name` and `stack`.
    //
    // NOT translated, and that is the fidelity rather than the drift: this catalog already carries its
    // technical nouns untranslated (`statusLive: 'Live'`, `statusWip: 'WIP'`, the `stack` chips, which
    // have no locale at all). "Lançamentos" would be the departure.
    viewReleases: { pt: 'Releases', en: 'Releases' },
    // Accessible name for the TAG variant, whose visible text is a bare `v0.1.166`. Same problem the
    // footer already solved (`footer.version`) and the same answer: a screen reader otherwise announces
    // a link named after a glyph and a version string, with no context and no external-link cue.
    //
    // Deliberately NOT reusing `footer.version` — that one says "the running build", which is right
    // beside the domain in the footer and wrong on a card, where the subject is the PROJECT rather than
    // the page you are reading. Same mechanism, different sentence.
    viewReleaseTag: {
      pt: 'Notas da release desta versão do projeto (GitHub)',
      en: 'Release notes for this version of the project (GitHub)',
    },
    // The `plugin-build` variant's accessible name (#345), and it is its OWN string rather than a reuse
    // of `viewReleaseTag` above — deliberately, because that one says "this version of the project" and
    // this card cannot claim that. Its tag is the plugin release the site was DEPLOYED AGAINST: exact
    // under that reading, and an overclaim under any other. It may not say "latest" or "current", which
    // is the wording a reader would supply for free if the sentence left room for it.
    // The PT edition is authored, not translated, and the first draft showed why that matters here. It
    // read `da release deste projeto COM QUE o site foi publicado` — and `com que`, sitting right after
    // `deste projeto`, parses first as "this project, with which the site was published". True, and a
    // DIFFERENT claim: it drops the one thing this key exists to name, which release. Fixed by removing
    // the competing noun rather than by repairing the relative: `com a qual` would have pinned it by
    // gender agreement, but `deste projeto` was borrowed from the sibling string above and names nothing
    // a reader of THIS card can see — the card shows a repo and a tag, never a "project".
    viewPluginReleaseTag: {
      pt: 'Notas da release com a qual este site foi publicado (GitHub)',
      en: 'Release notes for the release this site was deployed against (GitHub)',
    },
    emptyLead: { pt: 'Catálogo em construção.', en: 'Catalog under construction.' },
    emptyLink: { pt: 'Acompanhe no GitHub', en: 'Follow on GitHub' },
    viewAll: { pt: '→ Ver catálogo completo', en: '→ View the full catalog' },
    // This is the /portfolio OG description — the string LinkedIn, X and WhatsApp pin on FIRST fetch,
    // so it is the least reversible copy on the page.
    //
    // It used to promise "automações, agentes e projetos": three plural categories over a shelf holding
    // ONE item, and that item is none of the three — it is a static site. Same defect the bar sentence
    // was rewritten three times to remove, sitting in the meta description the whole while, and worse
    // there: a reader arriving from an unfurl that promised three kinds of thing and finding one is the
    // bait the body copy was being audited against.
    //
    // So it states the shelf's PURPOSE and its entry rule instead of enumerating a stock. True at one
    // item, true at twenty, and it does not need rewriting when the shelf grows.
    metaDescription: {
      pt: 'Código aberto pra estudar e clonar — e a régua que decide o que entra.',
      en: 'Open source to study and clone — and the bar that decides what gets listed.',
    },
  },
  contact: {
    heading: { pt: 'Algo aqui te ajudou? Me conta', en: 'Did something here help you? Tell me' },
  },
  contactLinks: {
    defaultTitle: { pt: 'Onde me encontrar', en: 'Where to find me' },
  },
  about: {
    heading: { pt: 'Sobre este site', en: 'About this site' },
    body: {
      pt: 'Escrevo e construo em público sobre engenharia de IA. Se algo aqui te ajudou a evoluir, cumpriu o papel.',
      en: 'I write and build in public about AI engineering. If something here helped you grow, it did its job.',
    },
    whoWrites: { pt: 'Quem escreve', en: 'Who writes this' },
  },
  cv: {
    experience: { pt: 'Experiência', en: 'Experience' },
    education: { pt: 'Formação', en: 'Education' },
    certifications: { pt: 'Certificações', en: 'Certifications' },
    // Not translated (owner, 2026-07-31). "Skills" is the word a pt-BR technical reader uses for this
    // section of a CV — "Habilidades" reads as a translation of a résumé template, not as the register
    // the rest of this page is written in. Same rule already applied to `agentic`, `AI-native` and the
    // harness vocabulary: the term stays English in both editions when English IS the pt-BR usage.
    skills: { pt: 'Skills', en: 'Skills' },
    present: { pt: 'Atual', en: 'Present' },
    unavailable: { pt: 'Perfil ainda não disponível.', en: 'Profile not available yet.' },
    // `journey` IS DELETED, NOT LEFT DORMANT (#516 slice 2b). It was the heading of the journey-photograph
    // block ("Percurso" / "Journey"), and that block stopped existing when the four photographs moved
    // inside the experience entries — where the entry's own dated employer heading is what a reader reads,
    // and a second heading would label nothing. Deleted rather than kept, for the same reason the retired
    // proficiency wording below was: `messages.test.ts` has NO orphan-key detection, so a catalog entry
    // whose only consumer is gone sits there green forever and reads to the next author as a string in use.
    download: { pt: 'Baixar CV (PDF)', en: 'Download CV (PDF)' },
    // RETIRED as of #317, and kept as strings rather than deleted only for the length of this comment:
    // these were the print-only proficiency wording for the one-page CV (#161). The meter was hidden in
    // print then, so a level-1 keyword printed beside a level-4 one as equals, and the calibration was
    // restated as words — on the LOW levels only, since those were the ones the flattening exaggerated.
    //
    // The meter is back on the sheet (#317), so the words became a second device saying the same thing,
    // and a one-sided one: every level 1–2 printed a diminishing gloss while every 3 and 4 printed bare.
    // On a recruiter artifact that reads as hedging the bottom of the list rather than rating all of it.
    //
    // Deleted rather than left dormant. A catalog entry with no consumer is the shape that gets
    // re-adopted by someone who finds it and assumes it is current — and if the meter is ever hidden in
    // print again, the reasoning above is what needs re-reading, not two strings that survived it.
  },
  // The locale OFFER (#172), shown when the URL's locale is not the visitor's own language. Every string
  // here is rendered in the SUGGESTED language, not the page's — it is addressed to a reader who may not
  // read the page's language at all, so writing it in that language would defeat the purpose. The region
  // therefore also carries its own `lang`, or a screen reader pronounces it with the wrong voice.
  localeSuggestion: {
    //
    // Register follows the rest of this catalog, which is first-person and informal ("pra", "me conta",
    // "te fazer construir melhor") — "Prefere ler em português?" read a notch more deferential than the
    // person who writes everything else on the page.
    //
    // The question names no language: between them the two buttons already do, and in a ten-word notice
    // each edition was otherwise named twice. The buttons carry the nouns, the question carries the ask.
    message: {
      pt: 'Esta página está em inglês. Quer trocar?',
      en: 'This page is in Portuguese. Want to switch?',
    },
    // Accept states its consequence rather than merely closing the notice — it also PERSISTS the choice,
    // overriding detection from then on, and a control that changes state should say what it changes to.
    accept: { pt: 'Ler em português', en: 'Read in English' },
    // Dismiss names the language too, for the same reason. "Continue", not "keep reading": a large share
    // of these readers arrive cold from a shared link and have not read anything yet.
    dismiss: { pt: 'Continuar em inglês', en: 'Continue in Portuguese' },
    // aria-label for the region.
    notice: { pt: 'Sugestão de idioma', en: 'Language suggestion' },
  },
  column: {
    loading: { pt: 'Carregando', en: 'Loading' },
    back: { pt: 'Voltar', en: 'Back' },
  },
  article: {
    notFoundTitle: { pt: 'Artigo não encontrado', en: 'Article not found' },
    notFoundBody: { pt: 'Este artigo não existe ou não está publicado.', en: 'This article does not exist or is not published.' },
    allArticles: { pt: '← Todos os artigos', en: '← All articles' },
  },
  share: {
    share: { pt: 'Compartilhar', en: 'Share' },
    copied: { pt: 'Copiado', en: 'Copied' },
    // The share deeplinks (#183). The heading stands alone and each target carries its OWN accessible
    // name — deliberately not one fragment concatenated in front of a platform name.
    //
    // pt-BR contracts the preposition with the platform's definite article: "no WhatsApp", "no X",
    // "no LinkedIn". A shared `'Compartilhar em'` + name yields "Compartilhar em WhatsApp", which is
    // English grammar wearing Portuguese words — and no rewording of the fragment fixes it, because the
    // contraction belongs to the pair, not to either half. English survives the same concatenation, which
    // is exactly why the defect would have shipped in one edition only.
    linksHeading: { pt: 'Compartilhar', en: 'Share' },
    onWhatsapp: { pt: 'Compartilhar no WhatsApp', en: 'Share on WhatsApp' },
    onX: { pt: 'Compartilhar no X', en: 'Share on X' },
    onLinkedin: { pt: 'Compartilhar no LinkedIn', en: 'Share on LinkedIn' },
    // aria-label for the group. Not "Share" — the page already has a ShareButton with that name, and two
    // controls whose accessible names are indistinguishable is the defect, not the duplication itself.
    linksLabel: { pt: 'Compartilhar este artigo', en: 'Share this article' },
    // #450. The same group's accessible name where the thing being shared is NOT an article — the share
    // block now also renders under `endMatter` on MarkdownPage, and /architecture is a section of this
    // site, so `linksLabel` would name it something it is not, to screen-reader users only.
    //
    // A SIBLING KEY RATHER THAN A REWORDED SHARED ONE, deliberately. Rewording `linksLabel` to "esta
    // página" is one key cheaper and wrong twice: it changes published copy on four live article pages
    // from inside a slice scoped to change one, and it loses precision where the current string is
    // correct — on an article, "este artigo" IS the better accessible name, and the distinction between
    // an article and a section is the thing this key exists to keep true. The cost is a key that can
    // drift from its sibling; it is bounded by messages.test.ts's both-locales assertion and by the two
    // sitting adjacent here, where a drift is visible in one screen.
    linksLabelPage: { pt: 'Compartilhar esta página', en: 'Share this page' },
    // #314. The modal's accessible name, and it must differ from `linksLabel` for the same reason that
    // one differs from `share.share`: on an article page the dialog and the footer nav are both share
    // groups, and a screen-reader user moving between landmarks cannot tell two identically-named
    // regions apart. "Options" is what the dialog adds — it is the one that offers a choice.
    modalLabel: { pt: 'Opções de compartilhamento', en: 'Share options' },
    // #409. THE FOOTER TRIGGER'S OWN NAME — the third control on an article page that had to stop being
    // called "Compartilhar", after `linksLabel` (the nav) and `modalLabel` (the dialog). The footer now
    // carries the modal trigger beside the deeplink block, and with `share.share` on both triggers the
    // page shipped two byte-identical buttons: the exact defect `linksLabel`'s comment above already
    // named and ruled against, one control lower.
    //
    // WHAT DISTINGUISHES IT FROM THE NAV BESIDE IT is not placement — it is the offer. `ShareLinks` is
    // the DIRECT destinations (copy-link, LinkedIn, X, WhatsApp, all reachable in one action); this
    // trigger opens `modalLabel`'s dialog, which is those four PLUS copy-as-markdown (#387). "Mais" is
    // that difference, and it is why reusing `linksLabel` — "Compartilhar este artigo", already exactly
    // the string this key wanted — was rejected: two controls sitting in the same row, one naming the
    // other's superset, is the collision re-created as a near-collision.
    //
    // TWO KEYS, AND THE SHORT ONE IS THE VISIBLE LABEL — the `copyLink` / `copyLinkToClipboard` shape
    // below, for the same reason and with a second one on top:
    //   1. The row is `text-xs uppercase` beside COPIAR LINK / LINKEDIN / X / WHATSAPP. A 31-character
    //      visible label there is the phone-row overflow that pair was split to avoid.
    //   2. WCAG 2.5.3 (Label in Name) requires the accessible name to CONTAIN the visible label, so the
    //      long form is built by extending the short one rather than replacing it — "Mais opções" ⊂
    //      "Mais opções de compartilhamento", "More options" ⊂ "More options for sharing". en takes
    //      `for sharing` and not `sharing options`, which would break the containment while reading
    //      almost identically; the pt word order gives it for free.
    //
    // AND THE VISIBLE LABEL HAD TO MOVE TOO, which is more than "a new accessible name" and is stated
    // rather than slipped in. Keeping "Compartilhar" visible while the accessible name differed would
    // fail 2.5.3 (per 2 above) AND still not fix the page, because Playwright matches an accessible name
    // by case-insensitive SUBSTRING — any name containing "Compartilhar" keeps two buttons under the
    // header's own locator. Neither of the two strings may contain "Compartilhar" / "Share", and
    // "compartilhamento" / "sharing" do not (`compartilhar` is not a substring of `compartilhamento`;
    // `share` is not a substring of `sharing`).
    moreOptions: { pt: 'Mais opções', en: 'More options' },
    moreOptionsLabel: {
      pt: 'Mais opções de compartilhamento',
      en: 'More options for sharing',
    },
    close: { pt: 'Fechar', en: 'Close' },
    // The fourth destination, and the only one that never leaves the page. pt says `link` rather than
    // `ligação` — `link` is the ordinary BR-Portuguese word here, and the same rule that keeps technical
    // nouns in English on the CV and the strip applies. NOT `url`: it is the more technical of the two,
    // and this site's register is deliberately not discouraging to a lay reader.
    //
    // STILL THE FOOTER'S LABEL, UNCHANGED, and that is a decision rather than an oversight (#387).
    copyLink: { pt: 'Copiar link', en: 'Copy link' },
    // THE MODAL'S PAIR, where the destination is named — owner-ratified verbatim.
    //
    // A SEPARATE KEY, not a rewrite of `copyLink`, because the reason the label grew is COMPARATIVE: two
    // adjacent rows reading "Copiar link" / "Copiar markdown" offer a choice of FORMAT and state no
    // destination, so `área de transferência` / `clipboard` is what makes the destination obvious. In the
    // footer there is no second row beside it — the copy-as-markdown option is modal-only — so the
    // justification does not reach there, and the first revision of this slice propagated the label
    // anyway: 40 characters in a `text-xs` uppercase row beside LINKEDIN / X / WHATSAPP, ~310px of a
    // ~335px phone row, wrapping onto its own line. The label would have grown 3.5× exactly where its
    // argument does not apply, in the one placement whose job is distribution.
    //
    // The cost of two keys is that a future rewording has to touch both. That is the right cost: they say
    // the same thing for different reasons, and the day the footer gains a second copy row it should
    // adopt this key rather than have its own quietly drift.
    copyLinkToClipboard: {
      pt: 'Copiar link para a área de transferência',
      en: 'Copy link to clipboard',
    },
    copyMarkdown: {
      pt: 'Copiar markdown para a área de transferência',
      en: 'Copy markdown to clipboard',
    },
    // THE FAILURE HAS TO BE VISIBLE (#387). A clipboard write is permission-sensitive and rejects in more
    // contexts than it looks — a non-secure origin, an embedded frame, a Safari call that lost its user
    // activation. Both copy paths used to swallow that in a `catch {}`, which is defensible for a
    // 60-character URL the reader can still select by hand, and indefensible for a payload they believe
    // is an entire article: they paste nothing and blame their notes app. `copied` stays the shared
    // success state for both controls.
    copyFailed: { pt: 'Não foi possível copiar', en: "Couldn't copy" },
    // The copied text's attribution line, directly under the generated title. WHICH URL IT CARRIES
    // DEPENDS ON THE CALLER, and this comment used to claim one shape for both: `ShareButton` (#387) cites
    // the canonical path, clean and UTM-free for the reason argued at length in `shareMarkdown.ts`;
    // `DraftReviewBar` (#506) cites the same path with `?preview` appended, because the reviewer's article
    // is held while he is reviewing it and a clean citation would redirect him to the locale home from
    // inside the review he is writing. Stated as two shapes rather than corrected to one: the divergence
    // is deliberate, and ADR-0049's amendment records the counter-argument it was taken against.
    source: { pt: 'Fonte', en: 'Source' },
    // Stands in for the ` ```adr-index ` fence, which is EMPTY in source and expands into a live table
    // only in the renderer. Copied verbatim it is three backticks; copied through this it is the link the
    // page would have told you to follow anyway.
    adrIndexLink: {
      pt: 'Índice de decisões (ADRs), no repositório',
      en: 'Decision index (ADRs), in the repository',
    },
  },
  // #506 — the draft review bar. THESE FOUR STRINGS ARE READER-FACING ONLY BEHIND `?preview`: the bar
  // renders nowhere else, so NO VISITOR SEES THEM AT ANY URL THAT DOES NOT CARRY THE PARAMETER. Stated
  // here because that is what keeps the slice in the safe class, and it is a property of the render gate
  // in `ArticlePage`, not of the catalog — move the bar and this sentence stops being true.
  //
  // ~~so no visitor arriving at any published URL sees any of them~~ — STRUCK. It was false, and false in
  // the direction that reads as safer: `/en/blog/<slug>?preview` IS a published URL, and `ArticlePage`'s
  // gate carries no `draft` term. The gate is the parameter ALONE, deliberately (the owner's refinement,
  // recorded in ADR-0049's 2026-08-29 amendment) — so this comment was written against the narrower gate
  // that was considered and not built, which is the one way a safe-class claim can be wrong without
  // looking wrong.
  //
  // THE CORRECTED SENTENCE IS PINNED, which is why it can be trusted where the first one could not:
  // `ArticlePage.test.tsx`'s "renders NOTHING for a visitor with no preview parameter", and
  // `e2e/draft-review.spec.ts`'s "a published article shows nothing of it to an ordinary reader" —
  // the latter reading the whole rendered body text, so a control that lost its accessible name is
  // still caught.
  //
  // Written for ONE reader, and he is the owner. Every other string in this catalog is addressed to a
  // visitor; these are tooling labels, so they are plain and name the destination rather than being
  // inviting. They are still authored in both locales, because he reviews the pt and en editions of an
  // article side by side and a bar that switched language mid-review would read as a different page.
  review: {
    // The bar's accessible name. NOT "Rascunho": a published article reached with the parameter renders
    // this bar too — the gate is the parameter alone (see `ArticlePage`) — so naming it after the held
    // state would be a name that is sometimes false.
    label: { pt: 'Revisão do artigo', en: 'Article review' },
    // The VISIBLE label / the ACCESSIBLE NAME — the `share.moreOptions` / `moreOptionsLabel` shape and the
    // same WCAG 2.5.3 containment rule: the long form EXTENDS the short one rather than replacing it, so
    // 'Abrir a issue' is a substring of 'Abrir a issue deste artigo no GitHub', and 'Open the issue' of
    // 'Open the issue for this article on GitHub'. The short form is what fits the mono row beside the
    // copy control; the long one is what tells a screen-reader user the link leaves the site.
    //
    // THE TWO EDITIONS SAY THE SAME THING NOW, and they did not. pt read 'a issue de conteúdo' — naming
    // the Issue's TYPE — while en read 'the issue for this article' — naming its RELATION to the article.
    // Both were true, so nothing was false; but an ACCESSIBLE NAME is the one string where the two
    // editions have to be interchangeable, because the owner reads them side by side and a screen-reader
    // user gets only one of them. The relation is the more useful meaning to a reader, and the type
    // additionally exported this project's internal routing taxonomy (`content`-typed Issues) into a UI
    // label, where it means nothing to anyone who has not read the harness docs. pt takes the relation.
    //
    // `issue` STAYS IN THE pt STRING, AND THAT IS A DECISION RATHER THAN A DEFAULT — the first anglicism
    // of its kind in this catalog, so it is where the precedent gets set. It stays because the control
    // opens a GitHub **Issue**, which is that object's name on the destination page; 'chamado' or 'tarefa'
    // would name something the reader will not find when they arrive. The same rule already keeps `link`
    // rather than `ligação` two groups down.
    openIssue: { pt: 'Abrir a issue', en: 'Open the issue' },
    openIssueLabel: {
      pt: 'Abrir a issue deste artigo no GitHub',
      en: 'Open the issue for this article on GitHub',
    },
    // NAMES THE ARTICLE, not the format. `share.copyMarkdown` names its destination because a second copy
    // row sits beside it offering the same destination in another format; here there is one clipboard
    // control and the question it answers is "the whole piece, or the link" — so the noun that
    // disambiguates is the article, and the destination stays implicit as it does in `share.copyLink`.
    copyText: { pt: 'Copiar o texto do artigo', en: 'Copy the article text' },
  },
  video: {
    play: { pt: 'Reproduzir vídeo', en: 'Play video' },
    watch: { pt: '▶ Assistir', en: '▶ Watch' },
    defaultTitle: { pt: 'Vídeo', en: 'Video' },
    // The link-preview form, for a video whose owner disabled embedding. The GLYPH is the
    // load-bearing difference from `watch` above and is not decoration: `▶` is the play affordance, and
    // reusing it on a control that navigates away is precisely the pretence the preview exists to stop.
    // `↗` is the outbound mark, and the destination is NAMED — a reader deciding whether to click needs
    // to know they are leaving, and "Watch" alone does not say so on either control.
    openOnYoutube: { pt: 'Assistir no YouTube ↗', en: 'Watch on YouTube ↗' },
    // States the FACT, not our inference from it. The channel disabled embedded playback; that is what
    // YouTube reports and all this repository knows. It deliberately does not say "unavailable" (it is
    // available, elsewhere) and does not apologise for a third party's setting.
    embeddingDisabled: {
      pt: 'Reprodução incorporada desativada pelo canal',
      en: 'Embedded playback disabled by the channel',
    },
  },
  consent: {
    notice: { pt: 'Aviso de cookies', en: 'Cookie notice' },
    message: {
      pt: 'Uso o Google Analytics pra entender o que é lido por aqui. Ele só carrega se você aceitar — nada de terceiros roda antes disso.',
      en: 'I use Google Analytics to understand what gets read here. It only loads if you accept — nothing third-party runs before that.',
    },
    accept: { pt: 'Aceitar', en: 'Accept' },
    reject: { pt: 'Recusar', en: 'Decline' },
    learnMore: { pt: 'Como o Google usa esses dados', en: 'How Google uses this data' },
    manage: { pt: 'Preferências de cookies', en: 'Cookie preferences' },
  },
} satisfies Record<string, Record<string, Entry>>;

export { strings };

/** Dot-path union of every string leaf — so `t('nav.articles')` is checked and a typo is a compile error. */
export type MessageKey = LeafPaths<typeof strings>;

type LeafPaths<T> = {
  [K in keyof T & string]: T[K] extends Entry ? K : T[K] extends object ? `${K}.${LeafPaths<T[K]>}` : never;
}[keyof T & string];

/** Resolve a dot-path key to the string for the active locale. */
export function translate(locale: Locale, key: MessageKey): string {
  let node: unknown = strings;
  for (const part of key.split('.')) {
    node = (node as Record<string, unknown>)[part];
  }
  return (node as Entry)[locale];
}
