// The typed message catalog — EVERY UI-chrome string. Key-first: each string carries BOTH locales
// adjacent ({ pt, en }), so there is no parallel per-locale block (which duplication detectors read as
// duplicated code) and adding a key can't miss a locale (the `satisfies` below makes it a compile error).
// The CV *content* is NOT here — it lives in src/data/profile.ts, authored bilingually in the same
// key-first shape and flattened by `resolveProfile`. Two catalogs, one convention: this one for chrome,
// that one for the CV, so chrome and content are in the visitor's language together.
import type { Locale } from './config';

/** One UI-chrome string in both locales. */
export interface Entry {
  pt: string;
  en: string;
}

const strings = {
  nav: {
    // The skip link (#250). It lives here, not in an a11y group, because this catalog groups by WHERE a
    // string appears rather than why it exists — `nav.openMenu`, `locale.switch`, `share.linksLabel` and
    // `consent.notice` are all accessibility-only strings sitting in their surface group. A second axis
    // would give the next aria-label two plausible homes and make neither reliable to search.
    //
    // BOTH editions name the destination without ranking it — "content", not "main content". That is a
    // catalog-wide choice, not a translation note: en dropped "main" too.
    skipToContent: { pt: 'Pular para o conteúdo', en: 'Skip to content' },
    articles: { pt: 'Artigos', en: 'Articles' },
    portfolio: { pt: 'Portfólio', en: 'Portfolio' },
    contact: { pt: 'Contato', en: 'Contact' },
    profile: { pt: 'Perfil', en: 'Profile' },
    rampup: { pt: 'Ramp-up', en: 'Ramp-up' },
    architecture: { pt: 'Arquitetura', en: 'Architecture' },
    openMenu: { pt: 'Abrir menu', en: 'Open menu' },
    closeMenu: { pt: 'Fechar menu', en: 'Close menu' },
  },
  locale: {
    // aria-label for the PT/EN toggle group.
    switch: { pt: 'Idioma', en: 'Language' },
  },
  footer: {
    // Accessible name for the version link. The visible text is a bare `v0.1.144` — conventional and
    // locale-neutral for a sighted reader, who gets the affordance from position and register. A screen
    // reader gets neither: it announces a link called "v0.1.144" with no context and no external-link
    // cue. So the number stays unlabelled on screen and the meaning lives here, which costs two catalog
    // entries and is the right trade in a file that is otherwise scrupulous about exactly this class of
    // thing (the skip link, the notice ordering, `tabIndex={-1}`).
    version: { pt: 'Notas da versão que está no ar (GitHub)', en: 'Release notes for the running build (GitHub)' },
  },
  adrTable: {
    // The generated decision index on /architecture (#318). Column headers and status labels live here
    // rather than in the markdown, because the TABLE is compiled from `docs/adr/` and only its chrome is
    // authored — putting the headers in each locale's markdown would mean the two editions could
    // disagree about what a column means while showing identical rows.
    // The PT caption says the records are in English, and the EN one does not — the asymmetry is the
    // point rather than a missing translation. Titles are canonical document names and stay in English
    // in both editions (a translated name would not exist at the other end of the click), so the PT
    // reader is the only one who meets 41 rows in a language the surrounding page is not. Signalling it
    // once in the caption costs a clause; leaving it unsaid makes the table look untranslated.
    // "generated … verified in CI", never "compiled at build". `npm run build` does NOT run `gen-adrs`
    // — the artifact is generated by its own command, committed, and checked by `adr-source.test.mjs`.
    // The paragraph above the table was corrected for exactly this and the caption was left carrying the
    // old claim, on the table itself, in both locales. Fixing one of two places is this slice's recurring
    // failure, and a caption is the copy a reader is most likely to take as the summary.
    caption: {
      pt: 'Índice de decisões, gerado a partir de docs/adr/ e conferido no CI — os registros são em inglês',
      en: 'Decision index, generated from docs/adr/ and verified in CI',
    },
    colId: { pt: 'ADR', en: 'ADR' },
    colTitle: { pt: 'Decisão', en: 'Decision' },
    colStatus: { pt: 'Situação', en: 'Status' },
    accepted: { pt: 'aceita', en: 'accepted' },
    superseded: { pt: 'substituída', en: 'superseded' },
    proposed: { pt: 'proposta', en: 'proposed' },
    rejected: { pt: 'rejeitada', en: 'rejected' },
    // Appended to a status, not replacing it: a decision that stands but has been revised is neither
    // plainly "accepted" nor superseded, and collapsing it to either loses the bit a reader needs.
    amended: { pt: 'emendada', en: 'amended' },
  },
  marquee: {
    // The key stays `subjects` — renaming it would touch every call site for no reader benefit —
    // but the LABEL is now "Stack", because that is what the strip lists. See Marquee.tsx.
    subjects: { pt: 'Stack', en: 'Stack' },
  },
  hero: {
    badge: { pt: 'Conteúdo técnico aberto', en: 'Open technical content' },
    badgeAccent: { pt: '▶ Da vida pessoal à produção', en: '▶ From personal life to production' },
    taglineLead: { pt: 'Aprenda a construir com IA —', en: 'Learn to build with AI —' },
    taglineAccent: { pt: 'do dia a dia à produção', en: 'from everyday life to production' },
    bodyLead: {
      pt: 'Compartilho o que aprendo construindo com IA — de experimentos que automatizam a',
      en: 'I share what I learn building with AI — from experiments that automate',
    },
    bodyStrong1: { pt: 'vida pessoal com Claude Cowork', en: 'personal life with Claude Cowork' },
    bodyConnector: { pt: 'a', en: 'to' },
    bodyStrong2: { pt: 'agentic development', en: 'agentic development' },
    bodyTail: {
      pt: '. Trade-offs reais e código aberto pra você aplicar, seja na sua rotina ou na sua empresa. O objetivo é te fazer construir melhor — quem escreve isso é consequência, não o ponto.',
      en: '. Real trade-offs and open source for you to apply, whether in your routine or at your company. The goal is to help you build better — who writes it is a by-product, not the point.',
    },
  },
  tracks: {
    pessoal: { pt: 'Vida pessoal', en: 'Personal life' },
    engenharia: { pt: 'Engenharia', en: 'Engineering' },
  },
  articles: {
    headingBold: { pt: 'Artigos', en: 'Articles' },
    headingRest: { pt: 'pra você aplicar', en: 'to put to use' },
    // The `· videos embedded in the text` half was dropped (owner, 2026-07-31). Both editions, because
    // this is one string with two renderings, not two decisions.
    //
    // The reason is stronger than "it promised a format rather than a payoff", which is what this
    // comment said first: NO ARTICLE DELIVERED IT. The capability exists (`hasVideo` in the
    // frontmatter, and the badge below fires per item) but not one published article sets it — the
    // embeds are on /ramp-up, a different route. So the storefront's highest-traffic section
    // advertised a property that zero of its rows carried. That is a capability stated as track
    // record, which the positioning rules out.
    //
    // The per-item `hasVideo` badge is the right home for the claim, and stays: it can only ever be
    // true, because it is rendered from the article that has one.
    subtitle: {
      pt: 'Escrita técnica com trade-offs explícitos',
      en: 'Technical writing with explicit trade-offs',
    },
    filtersLabel: { pt: 'Filtrar por trilha', en: 'Filter by track' },
    filterAll: { pt: 'Tudo', en: 'All' },
    takeaway: { pt: 'Você sai sabendo', en: "What you'll walk away with" },
    hasVideo: { pt: '▶ vídeo no artigo', en: '▶ video in the article' },
    read: { pt: 'Ler artigo', en: 'Read article' },
    viewOnLinkedin: { pt: 'Ver no LinkedIn', en: 'View on LinkedIn' },
    empty: { pt: 'Ainda não há artigos nesta trilha.', en: 'No articles in this track yet.' },
  },
  // The ramp-up page's chrome. Its BODY is markdown-in-repo, authored in both locales
  // (content/rampup.pt.md · content/rampup.en.md), so chrome and content are always in the same
  // language — the parity rule, not an interim.
  rampup: {
    heading: { pt: 'Ramp-Up — Virando AI Engineer', en: 'Ramp-Up — Becoming an AI Engineer' },
    // Document title (the site name is appended by useDocumentHead).
    title: { pt: 'Ramp-up para AI Engineer', en: 'Ramp-up to AI Engineer' },
    kicker: { pt: 'Plano aberto · em andamento', en: 'Open plan · in progress' },
    metaDescription: {
      pt: 'O plano que montei para migrar de arquiteto de aplicações cloud para AI Engineer: o raciocínio, os cinco pilares, o roadmap de 6–12 meses e as fontes que estou realmente usando.',
      en: 'The plan I built to move from cloud application architect to AI Engineer: the reasoning, the five pillars, the 6–12 month roadmap, and the sources I am actually using.',
    },
  },
  // The architecture page's chrome. Its BODY is markdown-in-repo, authored in both locales
  // (content/architecture.pt.md · content/architecture.en.md), so chrome and content are always in the
  // same language — the parity rule. The page is an orientation layer that LINKS canonical detail
  // (the ADRs, the two public repos, catalog-ready) rather than restating it.
  architecture: {
    heading: { pt: 'Arquitetura — a planta, em aberto', en: 'Architecture — the blueprint, in the open' },
    // Document title (the site name is appended by useDocumentHead).
    title: { pt: 'Como este site é construído', en: 'How this site is built' },
    kicker: { pt: 'A planta · aberta', en: 'The blueprint · open' },
    metaDescription: {
      // `agent-led verification` stays English in both locales, like `agentic` and `AI-native` (#245).
      // This string translated it while `architecture.pt.md` keeps the term with a gloss — so the pt
      // reader met the canonical term in the body and NEVER in the OG card, which is the text a scraper
      // pins. One term, two treatments, and the split landed in the surface with the worst correction
      // cost. The gloss stays in the body, where there is room to teach it.
      // Term FIRST, stack after. It used to sit around character 120 — inside the window LinkedIn, X and
      // SERP previews cut — so the fix that put the canonical term in the pt card left it invisible in a
      // large share of the cards it was meant to fix. The en string reached it earlier and was safer,
      // which is why the defect was only in one edition.
      // "as decisões que sustentam peso" / "the load-bearing decisions", NOT "cada" / "every" — the page
      // this describes qualifies it twice in both editions, and repoCards.ts carries the same correction on
      // the card that links the same library. A meta line is the one place the qualifier is cheapest to
      // drop and the claim hardest for a reader to check against the page it summarises.
      pt: 'Como este site é construído: o dev-loop de agent-led verification, a SPA estática em S3 + CloudFront, o conteúdo em markdown no repo prerenderizado no build, e os ADRs que registram as decisões que sustentam peso — com links para replicar.',
      en: 'How this site is built: the static SPA on S3 + CloudFront, markdown-in-repo content prerendered at build, the agent-led verification dev-loop, and the ADRs that record the load-bearing decisions — with links to replicate it.',
    },
  },
  portfolio: {
    heading: { pt: 'Portfólio', en: 'Portfolio' },
    // `se formam`, not `graduam`: in BR Portuguese this sense of `graduar` is pronominal, so the bare
    // form is the English intransitive wearing a Portuguese ending — the same defect class as the
    // "clarear a barra" draft this section's bar line went through. Shipped copy, found only because
    // the line above it was under review.
    // Dropped the definite article in both editions too: "as automações" / "the automations"
    // presupposes a set the reader has not been shown.
    intro: {
      pt: 'Código aberto pra você estudar, clonar e usar. Cresce conforme automações se formam.',
      en: 'Open source for you to study, clone and use. It grows as automations graduate.',
    },
    // The BAR (#246). With one item in the catalog — and that item being this site — the page reads as a
    // catalog that has not started. Saying inclusion is earned turns "the only item" into "the first item
    // that cleared the bar", which is a different claim to someone deciding whether the list is thin or
    // selective. It costs nothing to keep true: `docs/catalog-ready.md` already exists and is public, so
    // the sentence points at something checkable rather than making a promise to maintain.
    // Three drafts, and each one failed differently — worth recording, because the failures are the
    // reasoning:
    //
    // 1. "clarear a barra" was not Portuguese. `clarear` means to lighten; it was a calque of "clear the
    //    bar" carrying nothing of crossing a threshold.
    // 2. "conquista seu lugar passando pela régua" fixed the language and matched `/architecture`'s NOUN
    //    (pt "A régua", en "The bar") but not its construction — there the verb takes the DOCUMENT
    //    ("passa por catalog-ready.md"). So the surfaces shared a word, not a shape. `passar pela régua`
    //    is also not the BR form (that is `passar na régua`), and `conquista seu lugar` sat a register
    //    above this section's voice, which is second-person and warm two lines up.
    // 3. Both of those asserted an AUDIT — "each project earned its place" quantifies over the catalog's
    //    contents, so a reader can falsify it by checking the one item against the linked checklist. They
    //    can, today: #252. A sentence whose job is to RAISE scrutiny has to survive being scrutinised.
    //
    // So this states the GOVERNANCE rather than the audit — the rule, not a verdict on each item.
    //
    // Be precise about what that buys, because an earlier version of this comment overclaimed it: it is
    // NOT logically weaker. "Nothing enters without passing X" is the contrapositive of "everything here
    // passed X" — same truth conditions, falsified by the same single counterexample. What it buys is
    // rhetorical: it foregrounds the standard instead of inviting an item-by-item audit, and it drops a
    // merit claim that read as self-congratulation with a one-item shelf. The claim still has to be TRUE
    // on the day it ships, which is why #252 comes first.
    //
    // en went through one more pass than pt. `clear` wants a threshold noun — you clear a bar, a hurdle —
    // and with the noun dropped it was left governing a bare filename, with a colon stranding a transitive
    // verb before the break. `/architecture` gets away with `clears docs/catalog-ready.md` only because an
    // appositive supplies the noun right after. So en uses a verb that natively takes a document as its
    // object, and `gets listed` for the flat, un-Latinate register `entrar` already has in pt.
    // FOURTH draft, and the third failure was the interesting one — it was not about language.
    //
    // "Nothing gets listed here without passing X" is a universal over the shelf's CONTENTS, and
    // /architecture publishes, in both editions, that "this site is the one entry that did not come
    // through it". With a one-item shelf, that item IS the exception — so a reader visiting both
    // surfaces meets a contradiction, and the link makes it worse rather than better, because clicking
    // it lands them on the section that spells the exception out.
    //
    // The scoping work in #255/#256/#258 did not rescue the universal; it made it harder to stand
    // behind, by putting the carve-out into published copy.
    //
    // So this names the STANDARD and quantifies nothing: there is a bar for getting listed, here it is,
    // go read it. It still does #246's job — it turns "the only item" into "a shelf with an entry
    // requirement" — and it is true whatever the shelf currently holds, including while the shelf holds
    // its own exception. It also matches /architecture's label exactly (pt "A régua", en "The bar"),
    // which is the cross-surface consistency the earlier drafts kept missing.
    bar: {
      pt: 'A régua pra entrar aqui:',
      en: 'The bar for getting listed here:',
    },
    // The link text is the filename, deliberately untranslated — it names the artifact rather than
    // describing it, so there is nothing to keep in sync between editions.
    // Path form, matching how `/architecture` names the same artifact. These are the two surfaces most
    // likely to be read together, and one document with two names across them is a small, avoidable drift.
    barLink: { pt: 'docs/catalog-ready.md', en: 'docs/catalog-ready.md' },
    payoff: { pt: 'O que você tira disso', en: 'What you take away' },
    statusLive: { pt: 'Live', en: 'Live' },
    statusWip: { pt: 'WIP', en: 'WIP' },
    viewGithub: { pt: 'Ver no GitHub', en: 'View on GitHub' },
    viewLive: { pt: 'Ver ao vivo', en: 'View live' },
    // Only for a card that shows NO tag (#329). Where a tag is shown it IS the label — a version string
    // is the same in every edition, so it is not localized, exactly like `name` and `stack`.
    //
    // NOT translated, and that is the fidelity rather than the drift: this catalog already carries its
    // technical nouns untranslated (`statusLive: 'Live'`, `statusWip: 'WIP'`, the `stack` chips, which
    // have no locale at all). "Lançamentos" would be the departure.
    viewReleases: { pt: 'Releases', en: 'Releases' },
    // Accessible name for the TAG variant, whose visible text is a bare `v0.1.166`. Same problem the
    // footer already solved (`footer.version`) and the same answer: a screen reader otherwise announces
    // a link named after a glyph and a version string, with no context and no external-link cue.
    //
    // Deliberately NOT reusing `footer.version` — that one says "the running build", which is right
    // beside the domain in the footer and wrong on a card, where the subject is the PROJECT rather than
    // the page you are reading. Same mechanism, different sentence.
    viewReleaseTag: {
      pt: 'Notas da release desta versão do projeto (GitHub)',
      en: 'Release notes for this version of the project (GitHub)',
    },
    // The `plugin-build` variant's accessible name (#345), and it is its OWN string rather than a reuse
    // of `viewReleaseTag` above — deliberately, because that one says "this version of the project" and
    // this card cannot claim that. Its tag is the plugin release the site was DEPLOYED AGAINST: exact
    // under that reading, and an overclaim under any other. It may not say "latest" or "current", which
    // is the wording a reader would supply for free if the sentence left room for it.
    viewPluginReleaseTag: {
      pt: 'Notas da release deste projeto com que o site foi publicado (GitHub)',
      en: 'Release notes for the project release this site was deployed against (GitHub)',
    },
    emptyLead: { pt: 'Catálogo em construção.', en: 'Catalog under construction.' },
    emptyLink: { pt: 'Acompanhe no GitHub', en: 'Follow on GitHub' },
    viewAll: { pt: '→ Ver catálogo completo', en: '→ View the full catalog' },
    // This is the /portfolio OG description — the string LinkedIn, X and WhatsApp pin on FIRST fetch,
    // so it is the least reversible copy on the page.
    //
    // It used to promise "automações, agentes e projetos": three plural categories over a shelf holding
    // ONE item, and that item is none of the three — it is a static site. Same defect the bar sentence
    // was rewritten three times to remove, sitting in the meta description the whole while, and worse
    // there: a reader arriving from an unfurl that promised three kinds of thing and finding one is the
    // bait the body copy was being audited against.
    //
    // So it states the shelf's PURPOSE and its entry rule instead of enumerating a stock. True at one
    // item, true at twenty, and it does not need rewriting when the shelf grows.
    metaDescription: {
      pt: 'Código aberto pra estudar e clonar — e a régua que decide o que entra.',
      en: 'Open source to study and clone — and the bar that decides what gets listed.',
    },
  },
  contact: {
    heading: { pt: 'Algo aqui te ajudou? Me conta', en: 'Did something here help you? Tell me' },
  },
  contactLinks: {
    defaultTitle: { pt: 'Onde me encontrar', en: 'Where to find me' },
  },
  about: {
    heading: { pt: 'Sobre este site', en: 'About this site' },
    body: {
      pt: 'Escrevo e construo em público sobre engenharia de IA. Se algo aqui te ajudou a evoluir, cumpriu o papel.',
      en: 'I write and build in public about AI engineering. If something here helped you grow, it did its job.',
    },
    whoWrites: { pt: 'Quem escreve', en: 'Who writes this' },
  },
  cv: {
    experience: { pt: 'Experiência', en: 'Experience' },
    education: { pt: 'Formação', en: 'Education' },
    certifications: { pt: 'Certificações', en: 'Certifications' },
    // Not translated (owner, 2026-07-31). "Skills" is the word a pt-BR technical reader uses for this
    // section of a CV — "Habilidades" reads as a translation of a résumé template, not as the register
    // the rest of this page is written in. Same rule already applied to `agentic`, `AI-native` and the
    // harness vocabulary: the term stays English in both editions when English IS the pt-BR usage.
    skills: { pt: 'Skills', en: 'Skills' },
    present: { pt: 'Atual', en: 'Present' },
    unavailable: { pt: 'Perfil ainda não disponível.', en: 'Profile not available yet.' },
    download: { pt: 'Baixar CV (PDF)', en: 'Download CV (PDF)' },
    // RETIRED as of #317, and kept as strings rather than deleted only for the length of this comment:
    // these were the print-only proficiency wording for the one-page CV (#161). The meter was hidden in
    // print then, so a level-1 keyword printed beside a level-4 one as equals, and the calibration was
    // restated as words — on the LOW levels only, since those were the ones the flattening exaggerated.
    //
    // The meter is back on the sheet (#317), so the words became a second device saying the same thing,
    // and a one-sided one: every level 1–2 printed a diminishing gloss while every 3 and 4 printed bare.
    // On a recruiter artifact that reads as hedging the bottom of the list rather than rating all of it.
    //
    // Deleted rather than left dormant. A catalog entry with no consumer is the shape that gets
    // re-adopted by someone who finds it and assumes it is current — and if the meter is ever hidden in
    // print again, the reasoning above is what needs re-reading, not two strings that survived it.
  },
  // The locale OFFER (#172), shown when the URL's locale is not the visitor's own language. Every string
  // here is rendered in the SUGGESTED language, not the page's — it is addressed to a reader who may not
  // read the page's language at all, so writing it in that language would defeat the purpose. The region
  // therefore also carries its own `lang`, or a screen reader pronounces it with the wrong voice.
  localeSuggestion: {
    //
    // Register follows the rest of this catalog, which is first-person and informal ("pra", "me conta",
    // "te fazer construir melhor") — "Prefere ler em português?" read a notch more deferential than the
    // person who writes everything else on the page.
    //
    // The question names no language: between them the two buttons already do, and in a ten-word notice
    // each edition was otherwise named twice. The buttons carry the nouns, the question carries the ask.
    message: {
      pt: 'Esta página está em inglês. Quer trocar?',
      en: 'This page is in Portuguese. Want to switch?',
    },
    // Accept states its consequence rather than merely closing the notice — it also PERSISTS the choice,
    // overriding detection from then on, and a control that changes state should say what it changes to.
    accept: { pt: 'Ler em português', en: 'Read in English' },
    // Dismiss names the language too, for the same reason. "Continue", not "keep reading": a large share
    // of these readers arrive cold from a shared link and have not read anything yet.
    dismiss: { pt: 'Continuar em inglês', en: 'Continue in Portuguese' },
    // aria-label for the region.
    notice: { pt: 'Sugestão de idioma', en: 'Language suggestion' },
  },
  column: {
    loading: { pt: 'Carregando', en: 'Loading' },
    back: { pt: 'Voltar', en: 'Back' },
  },
  article: {
    notFoundTitle: { pt: 'Artigo não encontrado', en: 'Article not found' },
    notFoundBody: { pt: 'Este artigo não existe ou não está publicado.', en: 'This article does not exist or is not published.' },
    allArticles: { pt: '← Todos os artigos', en: '← All articles' },
  },
  share: {
    share: { pt: 'Compartilhar', en: 'Share' },
    copied: { pt: 'Copiado', en: 'Copied' },
    // The share deeplinks (#183). The heading stands alone and each target carries its OWN accessible
    // name — deliberately not one fragment concatenated in front of a platform name.
    //
    // pt-BR contracts the preposition with the platform's definite article: "no WhatsApp", "no X",
    // "no LinkedIn". A shared `'Compartilhar em'` + name yields "Compartilhar em WhatsApp", which is
    // English grammar wearing Portuguese words — and no rewording of the fragment fixes it, because the
    // contraction belongs to the pair, not to either half. English survives the same concatenation, which
    // is exactly why the defect would have shipped in one edition only.
    linksHeading: { pt: 'Compartilhar', en: 'Share' },
    onWhatsapp: { pt: 'Compartilhar no WhatsApp', en: 'Share on WhatsApp' },
    onX: { pt: 'Compartilhar no X', en: 'Share on X' },
    onLinkedin: { pt: 'Compartilhar no LinkedIn', en: 'Share on LinkedIn' },
    // aria-label for the group. Not "Share" — the page already has a ShareButton with that name, and two
    // controls whose accessible names are indistinguishable is the defect, not the duplication itself.
    linksLabel: { pt: 'Compartilhar este artigo', en: 'Share this article' },
    // #314. The modal's accessible name, and it must differ from `linksLabel` for the same reason that
    // one differs from `share.share`: on an article page the dialog and the footer nav are both share
    // groups, and a screen-reader user moving between landmarks cannot tell two identically-named
    // regions apart. "Options" is what the dialog adds — it is the one that offers a choice.
    modalLabel: { pt: 'Opções de compartilhamento', en: 'Share options' },
    close: { pt: 'Fechar', en: 'Close' },
    // The fourth destination, and the only one that never leaves the page. pt says `link` rather than
    // `ligação` — `link` is the ordinary BR-Portuguese word here, and the same rule that keeps technical
    // nouns in English on the CV and the strip applies.
    copyLink: { pt: 'Copiar link', en: 'Copy link' },
  },
  video: {
    play: { pt: 'Reproduzir vídeo', en: 'Play video' },
    watch: { pt: '▶ Assistir', en: '▶ Watch' },
    defaultTitle: { pt: 'Vídeo', en: 'Video' },
  },
  consent: {
    notice: { pt: 'Aviso de cookies', en: 'Cookie notice' },
    message: {
      pt: 'Uso o Google Analytics pra entender o que é lido por aqui. Ele só carrega se você aceitar — nada de terceiros roda antes disso.',
      en: 'I use Google Analytics to understand what gets read here. It only loads if you accept — nothing third-party runs before that.',
    },
    accept: { pt: 'Aceitar', en: 'Accept' },
    reject: { pt: 'Recusar', en: 'Decline' },
    learnMore: { pt: 'Como o Google usa esses dados', en: 'How Google uses this data' },
    manage: { pt: 'Preferências de cookies', en: 'Cookie preferences' },
  },
} satisfies Record<string, Record<string, Entry>>;

export { strings };

/** Dot-path union of every string leaf — so `t('nav.articles')` is checked and a typo is a compile error. */
export type MessageKey = LeafPaths<typeof strings>;

type LeafPaths<T> = {
  [K in keyof T & string]: T[K] extends Entry ? K : T[K] extends object ? `${K}.${LeafPaths<T[K]>}` : never;
}[keyof T & string];

/** Resolve a dot-path key to the string for the active locale. */
export function translate(locale: Locale, key: MessageKey): string {
  let node: unknown = strings;
  for (const part of key.split('.')) {
    node = (node as Record<string, unknown>)[part];
  }
  return (node as Entry)[locale];
}
