// YouTube facade (/frontend/markdown). Videos live INSIDE articles, never as a section of their own.
// The facade renders a LOCAL poster and only swaps in the iframe on click, so a page with a video
// ships zero third-party frames, cookies or requests until the reader asks for one.
//
// "Local" is the correction, and it is the whole point of the comment. This used to render
// `https://i.ytimg.com/vi/<id>/hqdefault.jpg`, which is a GET to a Google host on render — `lazy`
// defers it to the viewport, it does not condition it on intent. The sentence above was false on the
// word `requests`, and so were four sentences on /architecture that say analytics is the only third
// party at runtime. The poster is now generated by scripts/gen-video-thumbs.mjs and committed to
// public/video/<id>.png; scripts/video-thumbs.test.mjs fails if a video ships without one.
//
// A SECOND FORM: a video whose owner has disabled embedding cannot play in an iframe at
// all, so for that video the facade renders a LINK PREVIEW instead of a player. The defect that
// produced it is worth stating, because its shape is why it reached a published page — the facade is
// correct in every build, every test and every review, and fails only AFTER a reader clicks: the
// iframe loads, and YouTube renders "Video unavailable" inside a cross-origin frame nothing here can
// read. Nothing in this repository had ever checked whether ANY embedded video plays.
import { useState } from 'react';
import { useT } from '../i18n';
import videos from '../content/videos.json';

/** Accepts the watch, short and embed forms; returns the 11-char id, or null when it isn't YouTube. */
export function youtubeId(url: string): string | null {
  const m = /^https?:\/\/(?:www\.)?(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([\w-]{11})(?:[?&#].*)?$/.exec(url);
  return m ? m[1] : null;
}

/** The watch page for an id — the preview's destination, and the only off-origin URL it carries. */
export const watchUrl = (id: string) => `https://www.youtube.com/watch?v=${id}`;

/**
 * The manifest's shape as this component reads it. `channel` is listed although nothing here renders
 * it: an interface carrying only optional keys is a WEAK TYPE, and TypeScript rejects assigning the
 * imported JSON to it because no entry has a property in common. The required key is what makes the
 * assignment mean "these are the same objects" rather than "these happen to be compatible".
 */
interface VideoEntry {
  channel: string;
  /** The poster ART's caption — short, sized for a 1280x720 card by scripts/gen-video-thumbs.mjs. */
  caption?: string;
  /**
   * The video's OWN NAME, for the link card. Separate from `caption` on purpose, and the separation
   * was found by looking at the rendered page: with one field driving both, the poster art and the
   * card title said the same words twice, side by side. They are different objects — one is art text
   * sized to a fixed canvas, the other is prose a reader reads — and a field serving both makes the
   * shorter constraint govern the longer one.
   */
  title?: string;
  embeddable?: boolean;
}

const manifest: Record<string, VideoEntry | undefined> = videos;

/**
 * Does this video's owner forbid embedding?
 *
 * DECLARED IN DATA, per video, never special-cased on an id inside this component — the fact lives in
 * `src/content/videos.json`, beside the channel and caption describing the same video, in the manifest
 * the poster generator already reads.
 *
 * THE VOCABULARY HAS NO `true`, AND THAT IS THE DESIGN RATHER THAN AN OMISSION. The only value the
 * schema accepts is `"embeddable": false`. Absent means UNKNOWN, and unknown renders the player — which
 * is exactly today's behaviour for the other ten videos, left unchanged rather than silently blessed.
 * Nothing has checked those ten, so nothing here claims they play.
 *
 * The reason to make `true` unspellable is that the two directions of a wrong flag cost wildly
 * different things. A wrong `false` shows a reader a link preview for a video that would have played:
 * a visible downgrade, on the page, reversible in one line. A wrong `true` shows a play button that
 * dies after a click — invisible to every build, every test and every reviewer, which is the defect
 * this exists to fix. Removing the dangerous direction from the vocabulary is the only guarantee here
 * that does not depend on someone having remembered to check.
 *
 * Two layers back that up rather than one. `scripts/video-thumbs.mjs`'s `invalidEmbeddable()` reds on
 * any value other than `false`, and this function treats anything that is not exactly `false` as
 * unknown — so a value that somehow slipped past the gate still degrades to the status quo instead of
 * to a claim.
 */
export function embeddingDisabled(id: string): boolean {
  return manifest[id]?.embeddable === false;
}

/** The manifest row for a video, or undefined. The card reads its title and source from here. */
export const videoEntry = (id: string): VideoEntry | undefined => manifest[id];

export function VideoEmbed({ id, title }: { id: string; title?: string }) {
  const t = useT();
  const label = title ?? t('video.defaultTitle');
  const [playing, setPlaying] = useState(false);

  // A LINK CARD, NOT A PLAYER — and the shape is the whole point of this branch.
  //
  // The first version of this kept the player's 16:9 box and centred a button in it with a disclaimer
  // underneath. The owner's reading of that: «igual a um player com disclaimer». He was right — a
  // centred control in a wide box IS a player, whatever the button says, and adding an explanation to
  // something shaped like a player just makes a player with an excuse.
  //
  // So this is horizontal: a thumbnail beside a title and a source line, which is what a link preview
  // looks like. Nothing is centred and nothing is button-shaped.
  //
  // WHY THE IMAGE IS STILL OURS. He asked for the link's native OG preview. That is technically
  // available — the watch page serves `og:image`, and this site sets no CSP — and it is not taken,
  // because it is a request to a Google host on render. Two sentences published on /architecture, in
  // both locales, say the only third party at runtime is analytics and that it is consent-gated; and
  // this exact host was removed once already for making them false (see the header above). The card
  // shape and the image source are separable, and only the image costs anything, so the shape is taken
  // and the image is not. The title is the video's real name, which is what makes a card read as a
  // preview rather than a decorated link — and it is authored in `videos.json`, not fetched.
  if (embeddingDisabled(id)) {
    const entry = videoEntry(id);
    // The video's own name where the manifest states one, then the poster caption, then the caller's
    // title, then the generic label. Never a bare id — a card titled with a hash reads as broken
    // rather than as a link, which is the failure this whole branch exists to avoid.
    const cardTitle = entry?.title || entry?.caption || label;
    return (
      <a
        href={watchUrl(id)}
        target="_blank"
        rel="noreferrer"
        data-testid="video-preview"
        className="group my-6 flex w-full flex-col border border-border no-underline sm:flex-row"
      >
        {/* The poster, at THUMBNAIL scale rather than full-bleed. Decorative: the card states the
            video's name in text right beside it, so an alt would be a duplicate label. */}
        <img
          src={`/video/${id}.png`}
          alt=""
          aria-hidden="true"
          loading="lazy"
          className="aspect-video w-full shrink-0 object-cover sm:w-[42%]"
        />
        {/* `min-w-0` is load-bearing at 320px: a flex item defaults to `min-width: auto` and refuses to
            shrink below its content, and this title is long. The same trap PortfolioSection.tsx
            records for an unbreakable repo name — see RepoCard's comment on the 64px overflow. */}
        <span className="flex min-w-0 flex-col justify-center gap-2 p-5">
          <span className="font-mono text-[0.65rem] uppercase tracking-[0.15em] text-foreground/70">
            youtube.com{entry?.channel ? ` · ${entry.channel}` : ''}
          </span>
          <span className="break-words text-[1.05rem] font-bold leading-tight tracking-[-0.01em] text-foreground">
            {cardTitle}
          </span>
          {/* THE TWO CUES THAT SURVIVE FROM THE PREVIOUS FORM, and they are the requirement rather
              than decoration: a reader must be able to tell BEFORE clicking that this opens elsewhere
              and will not play here. `text-foreground/…` on the span itself is load-bearing — this
              anchor sits inside `.markdown`, whose `a:hover` repaints the anchor near-black, and a span
              with no colour of its own INHERITS that and vanishes on hover. Found by looking at the
              rendered page, not by reading; a colour set on the element beats an inherited one
              whatever the ancestor selector's specificity. */}
          <span
            data-testid="video-preview-note"
            className="font-mono text-xs uppercase tracking-wider text-foreground/80"
          >
            {t('video.embeddingDisabled')}
          </span>
          {/* `group-hover:text-primary-foreground` is the SECOND instance of the same defect and was
              found the same way — by looking at the hovered card. `.markdown a:hover` paints this
              anchor's background with `primary`, and this line is `text-primary`: orange on orange,
              gone at the exact moment the reader is pointing at it. Every text line in this card now
              carries its own hover colour, and the contrast assertion sweeps ALL of them rather than
              the one line that failed first. */}
          <span
            data-testid="video-preview-cta"
            className="font-mono text-xs uppercase tracking-wider text-primary group-hover:text-primary-foreground group-hover:underline"
          >
            {t('video.openOnYoutube')}
          </span>
        </span>
      </a>
    );
  }

  return (
    <div className="my-6 aspect-video w-full border border-border">
      {playing ? (
        <iframe
          src={`https://www.youtube-nocookie.com/embed/${id}?autoplay=1`}
          title={label}
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
          className="h-full w-full"
        />
      ) : (
        <button
          type="button"
          onClick={() => setPlaying(true)}
          aria-label={`${t('video.play')}: ${label}`}
          className="group relative flex h-full w-full items-center justify-center bg-muted"
        >
          {/* Decorative, exactly as it was when this was YouTube's thumbnail: the poster is a visual
              affordance behind the button, and the prose immediately above each embed already names
              the video and its channel. `alt=""` + aria-hidden is unchanged by this slice. */}
          <img
            src={`/video/${id}.png`}
            alt=""
            aria-hidden="true"
            loading="lazy"
            className="absolute inset-0 h-full w-full object-cover opacity-70 transition-opacity group-hover:opacity-90"
          />
          <span className="relative z-10 border-2 border-border-strong bg-background px-5 py-2.5 font-mono text-sm uppercase tracking-wider group-hover:border-primary group-hover:bg-primary group-hover:text-primary-foreground">
            {t('video.watch')}
          </span>
        </button>
      )}
    </div>
  );
}
