// YouTube facade (/frontend/markdown). Videos live INSIDE articles, never as a section of their own.
// The facade renders a LOCAL poster and only swaps in the iframe on click, so a page with a video
// ships zero third-party frames, cookies or requests until the reader asks for one.
//
// "Local" is the correction, and it is the whole point of the comment. This used to render
// `https://i.ytimg.com/vi/<id>/hqdefault.jpg`, which is a GET to a Google host on render — `lazy`
// defers it to the viewport, it does not condition it on intent. The sentence above was false on the
// word `requests`, and so were four sentences on /architecture that say analytics is the only third
// party at runtime. The poster is now generated by scripts/gen-video-thumbs.mjs and committed to
// public/video/<id>.png; scripts/video-thumbs.test.mjs fails if a video ships without one.
//
// A SECOND FORM: a video whose owner has disabled embedding cannot play in an iframe at
// all, so for that video the facade renders a LINK PREVIEW instead of a player. The defect that
// produced it is worth stating, because its shape is why it reached a published page — the facade is
// correct in every build, every test and every review, and fails only AFTER a reader clicks: the
// iframe loads, and YouTube renders "Video unavailable" inside a cross-origin frame nothing here can
// read. Nothing in this repository had ever checked whether ANY embedded video plays.
import { useState } from 'react';
import { useT } from '../i18n';
import videos from '../content/videos.json';

/** Accepts the watch, short and embed forms; returns the 11-char id, or null when it isn't YouTube. */
export function youtubeId(url: string): string | null {
  const m = /^https?:\/\/(?:www\.)?(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([\w-]{11})(?:[?&#].*)?$/.exec(url);
  return m ? m[1] : null;
}

/** The watch page for an id — the preview's destination, and the only off-origin URL it carries. */
export const watchUrl = (id: string) => `https://www.youtube.com/watch?v=${id}`;

/**
 * The manifest's shape as this component reads it. `channel` is listed although nothing here renders
 * it: an interface carrying only optional keys is a WEAK TYPE, and TypeScript rejects assigning the
 * imported JSON to it because no entry has a property in common. The required key is what makes the
 * assignment mean "these are the same objects" rather than "these happen to be compatible".
 */
interface VideoEntry {
  channel: string;
  caption?: string;
  embeddable?: boolean;
}

const manifest: Record<string, VideoEntry | undefined> = videos;

/**
 * Does this video's owner forbid embedding?
 *
 * DECLARED IN DATA, per video, never special-cased on an id inside this component — the fact lives in
 * `src/content/videos.json`, beside the channel and caption describing the same video, in the manifest
 * the poster generator already reads.
 *
 * THE VOCABULARY HAS NO `true`, AND THAT IS THE DESIGN RATHER THAN AN OMISSION. The only value the
 * schema accepts is `"embeddable": false`. Absent means UNKNOWN, and unknown renders the player — which
 * is exactly today's behaviour for the other ten videos, left unchanged rather than silently blessed.
 * Nothing has checked those ten, so nothing here claims they play.
 *
 * The reason to make `true` unspellable is that the two directions of a wrong flag cost wildly
 * different things. A wrong `false` shows a reader a link preview for a video that would have played:
 * a visible downgrade, on the page, reversible in one line. A wrong `true` shows a play button that
 * dies after a click — invisible to every build, every test and every reviewer, which is the defect
 * this exists to fix. Removing the dangerous direction from the vocabulary is the only guarantee here
 * that does not depend on someone having remembered to check.
 *
 * Two layers back that up rather than one. `scripts/video-thumbs.mjs`'s `invalidEmbeddable()` reds on
 * any value other than `false`, and this function treats anything that is not exactly `false` as
 * unknown — so a value that somehow slipped past the gate still degrades to the status quo instead of
 * to a claim.
 */
export function embeddingDisabled(id: string): boolean {
  return manifest[id]?.embeddable === false;
}

export function VideoEmbed({ id, title }: { id: string; title?: string }) {
  const t = useT();
  const label = title ?? t('video.defaultTitle');
  const [playing, setPlaying] = useState(false);

  // THE PREVIEW MUST NOT PRETEND TO BE A PLAYER, and that is a requirement about what the reader can
  // tell BEFORE clicking, not about what happens after. Three things carry it and none is decorative:
  // the control is an <a> rather than a <button>, so the browser's status bar, its context menu and a
  // screen reader all announce a link to youtube.com; the play glyph is gone, replaced by the outbound
  // arrow; and a second line states in words that the channel disabled embedded playback. The poster is
  // the SAME committed local asset the player uses — self-authored, for the licensing reason
  // scripts/video-thumbs.mjs's header records — so this form fetches nothing new either.
  if (embeddingDisabled(id)) {
    return (
      <a
        href={watchUrl(id)}
        target="_blank"
        rel="noreferrer"
        data-testid="video-preview"
        aria-label={`${t('video.openOnYoutube')}: ${label}`}
        className="group relative my-6 flex aspect-video w-full flex-col items-center justify-center gap-2 border border-border bg-muted no-underline"
      >
        {/* Decorative, exactly as in the player branch below. */}
        <img
          src={`/video/${id}.png`}
          alt=""
          aria-hidden="true"
          loading="lazy"
          className="absolute inset-0 h-full w-full object-cover opacity-70 transition-opacity group-hover:opacity-90"
        />
        <span className="relative z-10 border-2 border-border-strong bg-background px-5 py-2.5 font-mono text-sm uppercase tracking-wider group-hover:border-primary group-hover:bg-primary group-hover:text-primary-foreground">
          {t('video.openOnYoutube')}
        </span>
        {/* `text-foreground/80` IS LOAD-BEARING, and it was found by LOOKING rather than by reading.
            This anchor sits inside `.markdown`, whose `a:hover` rule repaints the anchor with
            `color: hsl(var(--primary-foreground))` — near-black. With no colour of its own this span
            INHERITED that and went black-on-black: the one sentence telling the reader the video opens
            elsewhere disappeared at the exact moment they pointed at it. A colour set on the span
            itself beats an inherited one whatever the selector's specificity, which is the same reason
            the chip above survives the same rule. */}
        <span className="relative z-10 max-w-[85%] bg-background/90 px-3 py-1 text-center font-mono text-xs uppercase tracking-wider text-foreground/80">
          {t('video.embeddingDisabled')}
        </span>
      </a>
    );
  }

  return (
    <div className="my-6 aspect-video w-full border border-border">
      {playing ? (
        <iframe
          src={`https://www.youtube-nocookie.com/embed/${id}?autoplay=1`}
          title={label}
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
          className="h-full w-full"
        />
      ) : (
        <button
          type="button"
          onClick={() => setPlaying(true)}
          aria-label={`${t('video.play')}: ${label}`}
          className="group relative flex h-full w-full items-center justify-center bg-muted"
        >
          {/* Decorative, exactly as it was when this was YouTube's thumbnail: the poster is a visual
              affordance behind the button, and the prose immediately above each embed already names
              the video and its channel. `alt=""` + aria-hidden is unchanged by this slice. */}
          <img
            src={`/video/${id}.png`}
            alt=""
            aria-hidden="true"
            loading="lazy"
            className="absolute inset-0 h-full w-full object-cover opacity-70 transition-opacity group-hover:opacity-90"
          />
          <span className="relative z-10 border-2 border-border-strong bg-background px-5 py-2.5 font-mono text-sm uppercase tracking-wider group-hover:border-primary group-hover:bg-primary group-hover:text-primary-foreground">
            {t('video.watch')}
          </span>
        </button>
      )}
    </div>
  );
}
